(import (chezscheme))

(define EXAMPLE
  '(((u u u x b b b) . (1 1 3))
    ((x u u x x u u x x x u b b x) . (1 1 3))
    ((u b u b u b u b u b u b u b u) . (1 3 1 6))
    ((u u u u x b x x x b x x x) . (4 1 1))
    ((u u u u x b b b b b b x x b b b b b x) . (1 6 5))
    ((u b b b u u u u u u u u) . (3 2 1))))

;; Counts how many broken sprinklers are next up in the record.
(define count-b
  (lambda (record)
    (let f ([r record] [i 0])
      (cond
       [(null? r) i]
       [(eq? (car r) 'b) (f (cdr r) (+ i 1))]
       [else i]))))

;; Produces #t if there are at least count number of b's or u's,
;; and it ends with a u or x.
(define can-consume-b?
  (lambda (record count)
    (let f ([r record] [i 0])
      (cond
       [(= i count) (or (null? r) (not (eq? (car r) 'b)))]
       [(null? r) #f]
       [(eq? (car r) 'x) #f]
       [else (f (cdr r) (+ i 1))]))))

;; Recursively descends into the decision tree to create arrangements, producing a count of
;; possible ones.
(define produce-arr
  (lambda (record counts hashmap)
    (if (hashtable-ref hashmap (cons record counts) #f)
        (hashtable-ref hashmap (cons record counts) #f)
        (cond
         [(null? counts)
          (let ([result (if (not (member 'b record)) 1 0)])
            (begin
              (hashtable-set! hashmap (cons record counts) result)
              result))]
         [(null? record)
          (let ([result (if (null? counts) 1 0)])
            (begin
              (hashtable-set! hashmap (cons record counts) result)
              result))]
         [(eq? (car record) 'u) (let* ([x-result (produce-arr (cons 'x (cdr record)) counts hashmap)]
                                       [b-result (produce-arr (cons 'b (cdr record)) counts hashmap)])
                                  (begin
                                    (hashtable-set! hashmap (cons (cons 'x (cdr record)) counts) x-result)
                                    (hashtable-set! hashmap (cons (cons 'b (cdr record)) counts) b-result)
                                    (+ x-result b-result)))]
         [(eq? (car record) 'x) (let ([result (produce-arr (cdr record) counts hashmap)])
                                  (begin
                                    (hashtable-set! hashmap (cons (cdr record) counts) result)
                                    result))]
         [(eq? (car record) 'b) (if (can-consume-b? record (car counts))
                                    (let* ([tail (list-tail record (car counts))]
                                           [new-record (if (null? tail) '() (cons 'x (cdr tail)))])
                                      (produce-arr new-record (cdr counts) hashmap))
                                    (begin
                                      (hashtable-set! hashmap (cons record counts) 0)
                                      0))]))))

(define expand-counts
  (lambda (ls copies)
    (let f ([i 0] [acc '()])
       (if (= i copies)
           acc
           (f (+ i 1) (append ls acc))))))

(define expand-springs
  (lambda (ls copies)
    (let f ([i 0] [acc '()])
      (cond
       [(= i copies) acc]
       [(null? acc) (f (+ i 1) (append ls acc))]
       [else (f (+ i 1) (append ls (cons 'u acc)))]))))

;; Calculates the number of arrangements for one record.
(define calculate-arr
  (lambda (row copies solns)
    (let ([record (expand-springs (car row) copies)]
          [counts (expand-counts (cdr row) copies)])
      (produce-arr record counts solns))))

;; Sums the number of different arrangments possible for each row in input.
(define solve
  (lambda (input copies)
    (let [(solns (make-hashtable equal-hash equal?))]
      (let f ([i input] [count 0] [acc 0])
        (if (null? i)
            acc
            (f (cdr i) (+ count 1) (+ acc (calculate-arr (car i) copies solns))))))))

(printf "~a~n" (solve EXAMPLE 1))
(printf "~a~n" (solve EXAMPLE 5))

(define INPUT
  '(((u u u x u u u u u u u ) . (1 4))
    ((u u u u u x x x b u u ) . (5 1))
    ((u u u u b x u u u u ) . (2 2 2))
    ((u u u u x u u b u x u x u u u u b ) . (3 4 1 1))
    ((b u u x b x u u u u u u b b u ) . (1 1 7))
    ((u u b b b u b b x u u u u u u b u u b x ) . (8 1 2 2))
    ((x u b b u u u u x b u u u ) . (3 4))
    ((x u b x b u b u u u x u b u u ) . (2 1 2 1 3))
    ((u u x x u u u u b x ) . (2 2))
    ((u b u u b u u x u u u b b u u x ) . (5 5))
    ((u b u b u u u u u u b u u ) . (4 1 1))
    ((u u x u u u u u u b ) . (1 6))
    ((b b u u x u u u u u u b ) . (2 1 3 2))
    ((u u u u u u u u b b u x b u u u u x u ) . (9 5))
    ((x u u u b u b u b b b u u b x x u u u ) . (13 2))
    ((u u x x x u u u u b b u u u ) . (1 6))
    ((u u u u u u b x u u u b u u u u x ) . (1 1 2 4 1))
    ((b x b u u x u u x b u u b x u u ) . (1 2 2 4 2))
    ((u x u u x u u u u u u u u u b ) . (2 2 3 1))
    ((u u x u x x b x u u u u u u u ) . (1 1 1 1 3))
    ((u b u b u b u u b u u u u b u ) . (2 1 4 1 2))
    ((u u b u x x b x x b ) . (2 1 1))
    ((u b u b u b u u u u u u u u u ) . (5 7))
    ((u u u x u u u u b u u ) . (1 3))
    ((x u u u u u u b u b x b x ) . (1 1 5 1))
    ((u u b u u u u u x u u u u u u x x u u ) . (7 1 3 1))
    ((u u b u u b u x u u u b u u ) . (5 1))
    ((u b u u u u u u u u u u b u b ) . (1 4 7))
    ((u x u b u x u u u u u ) . (3 1 2))
    ((u u b x u b x u u b u x ) . (1 1 1 2))
    ((u u u x u b b x u u ) . (2 3 1))
    ((u b x x x u u u u u u x u u x u x b ) . (2 2 2 1 1 1))
    ((x u b u u b u u u b b u u u u b u b x x ) . (11 3))
    ((b u b u x u u x u u u u u u u u u u u ) . (1 1 1 9))
    ((u x u x u b u x u u b u u u ) . (1 1 2 2))
    ((u u x x u u u u u b u u u u u ) . (1 6 2))
    ((u x u u x u u x u u u u u b u ) . (1 7))
    ((u b x u x u u u u b u u u x u b ) . (2 1 2 1 1))
    ((u u u x u u u u x x u u b u ) . (2 3 2))
    ((u u u b u u u b u u ) . (4 2))
    ((x b b x u b u u b u b u u b u ) . (2 4 1 3))
    ((x x u b u u b u x u u x ) . (5 2))
    ((u u u x u u x u u b u u u b u b u u ) . (2 2 1 3 3))
    ((x b u u b b u u u b x u u u u b x x u u ) . (1 3 1 1 3 1))
    ((u u u u u x b u x b u u u u ) . (2 2 1 1))
    ((x u b x u u u u u b u u ) . (1 6))
    ((x u u b u x u u u b u u x u u ) . (2 1))
    ((u b u u u u b b u u x u u u u ) . (2 1 4 2))
    ((u b u u u u x u u u x x u x u u u u u x ) . (1 3 1 3))
    ((b x u x u u u u x u x x u u x ) . (1 1 2 1 2))
    ((x u u b x u u b u b u u ) . (1 5))
    ((b b u u u u b b u u u b b u u u ) . (2 1 2 4))
    ((u u u b u u x x b u u b u u b x ) . (5 7))
    ((x x u x u x u u u u u ) . (1 1 1))
    ((x x b u u u u x u b u u ) . (1 1 1 3))
    ((u b u u u u x u b b b u u u u u u ) . (2 2 4 2 1))
    ((u u b x u x u b x b u b b u b b b u ) . (2 1 8))
    ((u u x b u u x u u x u u u u ) . (1 3 4))
    ((b u u u b u u u b u u x ) . (5 2))
    ((u x b u x u u u u u u u ) . (2 1))
    ((x u u u u b u u u u u u b u b u u u ) . (1 5 1 1 1 1))
    ((u b u u x u b u u b u u u u x u b u ) . (1 1 8 1))
    ((b x x u u u x x u b u u u u b b b x u ) . (1 2 9))
    ((u u u u b u b u u u u ) . (4 5))
    ((u u u u u b b b u u b u u u b u x ) . (4 7))
    ((u u u x b u u b u u ) . (1 1 4))
    ((u u u u b u u u u u b ) . (1 7))
    ((u u u u u u u u u b u u u b u b x u u ) . (2 1 5 1 2))
    ((u u u u u u u u u x u u x u ) . (2 3 2))
    ((u u u u x u u x x x ) . (1 1 1))
    ((u u u u u x x u u u u x u u u u x ) . (1 3))
    ((u u u x u u u u u u u u u u x b x u ) . (1 10 1 1))
    ((u b x u u u u u u u u b u u u u b u ) . (1 10 1))
    ((x u u u u u u x u b u u b x b u ) . (6 1 1 2))
    ((u u u x u u u u u u ) . (1 3 1))
    ((u x b u u u u u u u x u u u ) . (1 5 1))
    ((x u u u u b u b u b b u u u ) . (1 8))
    ((u u u u b u u u u b x u u ) . (1 1 3))
    ((b u u u u x u u u u b u b u u u ) . (1 1 2 4 1))
    ((u u u u b u x u u b u u u x u ) . (3 5))
    ((x u u b u u u x u u u u u u ) . (4 1))
    ((b u u b u x x u x x u x u x u ) . (1 3 1 1 1))
    ((u x x u u u u b u u u u u u b b u x x ) . (5 4))
    ((u b b u u u u u u b b u b u u b u ) . (4 9 1))
    ((u u b u x b u u b u u u u u u u ) . (3 2 3 2))
    ((u u u x b u u b u u u b u u u u b x ) . (1 2 2 1 1 1))
    ((u u u u u u u b u b u u b x u ) . (3 6))
    ((u u x u u u u b u b u x u u u ) . (2 7 1 1))
    ((x u u b b x u u u u u u u ) . (3 2 2))
    ((u x u u u x u u b u ) . (1 1 1))
    ((b u u b b u b u x u b u u u u u ) . (1 3 2 2 1))
    ((u u b u u u u b u u u u ) . (1 4))
    ((u u x x u x b u u x u u u u u u b u ) . (1 1 1 1 2 4))
    ((x u u u u u u u b x u u u u b u u ) . (1 2 1 1 3))
    ((u u u u u u b u u x u b ) . (6 1))
    ((u u u u b u u u u u b u u u u u u u u ) . (4 1 2 1 3))
    ((b b u u u u u u u u u ) . (2 2 2))
    ((x u b b u x u u u u ) . (3 1))
    ((u u u u b u u x u u u u u b u u ) . (5 3))
    ((u u u u u u u u b u u u u ) . (1 1 8))
    ((u u u b x u u u u u u u u b u ) . (2 7))
    ((u u u u u u u u b b x u ) . (2 2))
    ((u b x x u x u u u u u b u u u u ) . (1 1 3 3 1))
    ((u u u u u u u u u b b b u u x ) . (2 1 7))
    ((u u u u u b b u u u b b u b u b u u ) . (1 4 8))
    ((u u u u u u u u u u b u ) . (1 1 1 1))
    ((x u u u u u b u u u ) . (1 1 1))
    ((x u u u u u u u u u u ) . (2 1 2))
    ((x u u u x x b u u u u x u u ) . (3 1 1 1))
    ((u b u u u u b u u u u u u u ) . (1 5 2 1))
    ((u u u u u u u u u u b b u u ) . (4 2 5))
    ((b x u u u u u u u u u u u u ) . (1 7 3))
    ((u u b u u b u u x u b u u u u b ) . (5 6))
    ((x u b u u u u x b u u u u u u u u u b ) . (3 2 3 2))
    ((x b x x u u b u b u u u u x x u u ) . (1 9 2))
    ((u u x u u u b u u b u x u u ) . (4 2))
    ((u u b b u u u u u u b u x u b ) . (4 2 2 2))
    ((x u u u u u u u x u b u b u u u b u ) . (2 2 2 1 3))
    ((x u u b u b u b u u b u x u u u u b u ) . (10 5))
    ((x b u u b u u u b u u b b u x ) . (5 5))
    ((u u b u b u u u x u ) . (2 3))
    ((x x u u b u u u u u u b b u u b u u u ) . (3 8 1))
    ((u x u u x b x u u u b b x b b u u u b ) . (1 2 1 4 4 1))
    ((x b u x u u u u u u u b x ) . (2 4))
    ((x u u u u b b u u u u u u u u ) . (1 5 1))
    ((u u u u x x x b u u x u x ) . (1 1 2 1))
    ((u u u u u u b u b u u u u u ) . (1 8))
    ((u b x u x u x b u u u b b b ) . (1 1 1 7))
    ((b u b u x u u b u b u u b b u u ) . (1 1 1 9))
    ((x u x b u u b u u u x u x x b b u ) . (6 2))
    ((u u u u u u u u u u u b ) . (1 3 3))
    ((u u u b b u x b b u u u x u x u ) . (5 3 1 1 1))
    ((u u x u u u b b x u b b u u u u ) . (1 2 2 2 1))
    ((u u x b u u u u u u u u u u u x b ) . (1 1 1 6 1))
    ((x x u b b u b b u u u u u u b u ) . (7 5))
    ((u b u u u u u u u u ) . (1 1 1))
    ((u b u x u b u u u u ) . (1 4))
    ((u u b u u u u u b u b u x b u u ) . (8 1 3))
    ((u x u u u x u b u b b b u ) . (1 1 1 3))
    ((u b u b u u u u b b u u u u u u u u u ) . (3 5 2))
    ((b b u u u u u b u b b u u u u u x u u ) . (3 7 2 1))
    ((u u u u b x b u u u b ) . (1 1 5))
    ((x u u u u b u u u u u u u u ) . (1 3 4))
    ((u b u b x u b u b u ) . (2 1 4))
    ((u x u x u b u u b u b u ) . (1 2 3))
    ((u b u b b u u b u b b u u u u u u u ) . (12 2))
    ((x u u b x u u u u b u ) . (1 1 3))
    ((b u u u u x u b b b u u u u u ) . (2 1 8))
    ((u b u x u u u u u u ) . (1 1 1))
    ((u u u b u u u u b u ) . (3 1 3))
    ((u u u b u u x x u b u u x u x u u u ) . (6 4 2))
    ((b u u u u u u u b u x u u b u u u u u ) . (5 1 2 3 2))
    ((x b u u b u u b b u u u u ) . (4 4 1))
    ((x u u u u u u u u u u ) . (4 2 2))
    ((u x u b u u u u u u u u u x u u u ) . (1 9 1 1))
    ((u b u x b b u b b u u b b u b ) . (1 11))
    ((u u u b b u u u u u u u u u u u u ) . (5 2 2 4))
    ((u u u u u u u u u u u u b b u u u x ) . (2 2 6 1))
    ((x b u u b b b u u u x ) . (6 1))
    ((u x u b x u u b b u u u u u ) . (1 1 3 1))
    ((b u u x u u x u u u u u u u u u x ) . (1 1 1 1 6))
    ((x u u u b u b u u u u u ) . (1 4))
    ((u x b x x b u x x u b ) . (1 2 1))
    ((u u u u u u u u b u u u u x u u ) . (1 3 2 2 1))
    ((u b u b u u u x u u u x b u u u ) . (6 3 2))
    ((x u u u u x u u b u b u x x u u ) . (3 5))
    ((b u u u b u u b u b u u b u u x ) . (5 1 1 1 1))
    ((u u u x u x u u b u u u u u u b u u ) . (1 1 1 3 7))
    ((u u u u u b u b u u x b u u x ) . (6 3))
    ((u b u b b u u u b u u u u u u u u ) . (10 2))
    ((u u u u u b u u u u b u b b u u x u u ) . (1 3 7 1))
    ((x x x u u u u u u x ) . (1 1))
    ((b x u u u u u u b x ) . (1 1 1))
    ((u u x u b u u u u u x u u b u u u u u u ) . (1 3 2 2 3))
    ((u u u u b u u u u u b u u u ) . (1 8 1))
    ((u u u x u b b u u b u u u u u ) . (2 7 2))
    ((u x u u u u u u b u b u ) . (1 1 1 4))
    ((u u u u x u u b u u u b u u b u x b u b ) . (2 1 9 3))
    ((b u u u x u u u b u u u b u u u u b ) . (4 6 2))
    ((u u x x b b u b u u u u ) . (1 2 1 1))
    ((x u u u b u u u x u b u ) . (3 2))
    ((u b u u u u b u u x u b u u u b u u u u ) . (4 1 7 1))
    ((b u x u u u b u u u u b u u b u u u ) . (1 15))
    ((u u u u u u u x u u u b u u u u x ) . (4 1 4 1))
    ((u u b u u u u b u u u x x u u x u ) . (4 3 2 1))
    ((x u u x x u u u u u u u u ) . (1 1 2 1))
    ((u u u u u b u u u u u u u u u u u u ) . (1 3 3 3))
    ((u b u x u u u x u b u u u b u u x u b ) . (1 2 6 1 2))
    ((u u b u u b u u u b b ) . (2 2 3))
    ((u u b u b b u u u b u u ) . (1 3 3))
    ((u u u u u u u u b u u x u u u u u ) . (1 8 2))
    ((u u u x u u x u u u u u x u ) . (1 3))
    ((u b b u x u b u b b u u ) . (3 5 1))
    ((u u u u u u u x u u b u u b ) . (5 4 1))
    ((u u u b u u x u u u u ) . (1 3 4))
    ((x u u u u u x x u u u u u x u ) . (4 1))
    ((u u b b u u b u b u u x u ) . (6 1 1 1))
    ((x u u u u u u u b u u u b b u u b u ) . (5 2 8))
    ((u u u u b b b u u b b u u u u ) . (1 10))
    ((u b u x u b u u u u u u u b u x u b x ) . (1 2 3 1 1))
    ((b b u x b u u x u x u u u b b u u u ) . (3 1 1 1 2 1))
    ((u x x b u u u u u u u b b u u u u u ) . (5 4))
    ((u u b u b u u u b u x x u u u u x ) . (1 3 3 4))
    ((u u b u u x u b u u u ) . (2 5))
    ((x u u b u u u u b u u b u ) . (1 1 5 2))
    ((u u u u u u u u b x u u u b u ) . (3 1 2 1 1))
    ((u b u u x b u b u u u x ) . (1 3 1))
    ((u u u u u u u u b b u u x ) . (1 2 3))
    ((b u u u u b u u u u u u x ) . (3 2 1 1))
    ((u b x u u x u u u u b x x b ) . (1 1 3 1))
    ((b u u b u u b u u b u u u u u u b u u ) . (4 6 2 2))
    ((u u x u u b u x b u b b ) . (1 3 4))
    ((u u u u x b u u u u ) . (3 4))
    ((u u u u u u u x u u u u ) . (1 2))
    ((u x b u u u x x u x b u b x x u x ) . (1 2 1 3 1))
    ((u x u u u u u x u u b x u u ) . (1 1 2 2))
    ((x u u u u b u u b x u u u ) . (8 1))
    ((u u b u u u b u u u b b u u x u u b u u ) . (2 2 4 2 1))
    ((x u u u u u u u u u u x u b u u u b u ) . (2 5 6))
    ((u u x u u u u b b u u u u u u u ) . (1 12))
    ((u u u u u u b u x u b b u u x ) . (1 5 4))
    ((u u u u x u u u u u x ) . (1 1 1))
    ((u u u u u u x u x x u u b b u ) . (1 1 1 1 4))
    ((b u u b b u u u u u x u u ) . (1 3 1 1))
    ((x b b x x u b b u u x u u b b b ) . (2 4 5))
    ((b u u u u u u u x u u u u ) . (1 1 1 2))
    ((u u u u u x u u u u u ) . (2 1 1))
    ((b x u u x u b x u x u ) . (1 2))
    ((u x u u u u u u u x x b b b u u u u u u ) . (1 1 3 4 1 1))
    ((u x x u u x b b u x u u u ) . (1 2 2 1))
    ((u u b u u u u x x u u u u u b ) . (3 1 3))
    ((u u b u x u u u u b u x u u u x ) . (1 1 1 1 3))
    ((u u b x u u u x b u u u u b b b b ) . (2 1 1 6))
    ((u u b u u u x u x u u u u u b u ) . (5 1 1 1 1))
    ((u b u u u b x u u u u u ) . (6 1 1))
    ((u b u u x u u x u u u ) . (4 1 1))
    ((u u u u u u b u u u u u u u u ) . (6 2 1))
    ((u u x b u u x u u u b u u ) . (1 4))
    ((b u u x u b u u u x b u x ) . (2 4 2))
    ((u u b b u u u b x u u u ) . (1 2 3 2))
    ((u x u u u u u u u u u u b ) . (1 5 1 1))
    ((u b u u u u u b u x ) . (1 1 3))
    ((u u u u x u b b u u u ) . (1 4 1))
    ((x u u b x x u u u b b u b b u u b b u u ) . (2 10))
    ((u u b b u u u u b u u u x ) . (4 3))
    ((x u u b u u u b b u u ) . (2 3))
    ((b u u u x b u b u u u u u x u x x b u ) . (1 1 7 1 1))
    ((u b b u u b u u u u u u x x u ) . (3 2 1 1 1))
    ((u u u u u x u b u b u ) . (5 2 1))
    ((u u u x u u u u b u u ) . (2 3))
    ((u u u u x b u u u x u u u u ) . (1 3 1))
    ((u b u u u x u u u u ) . (1 1 2))
    ((u b x x u u x u u b u x x ) . (1 3))
    ((u u x u u b b b u u u u u u ) . (1 8 1))
    ((b u u u u b u u u x ) . (6 1))
    ((b x u u b b u u u u x u b u u u b ) . (1 6 1 1 1))
    ((u u u u b u u u u u x x b u ) . (7 1))
    ((u u u x u u b u u u u u u b ) . (1 1 4 4))
    ((b u u u b x u x x x u u x u ) . (5 1 1))
    ((u u u x u u u u u b u u b u u u x ) . (1 10))
    ((u u u u u u u b b u u b b u x u x u ) . (2 4 2 1))
    ((b x b x u u u u u u x u b u b u ) . (1 1 4 1 4))
    ((u x u u b b u u u u x ) . (1 2 2))
    ((u b u b b x u u u u x u x x u u ) . (5 1 1 2))
    ((x x u u u b u u u u b ) . (4 3))
    ((x u x u u u u u u b u u b u b u b x u ) . (7 6))
    ((u u b u u u b u b b u x u u u ) . (4 5 1))
    ((x b u x u u u u b u u b x u u ) . (1 1 6 1))
    ((u u b u u b u u u u u x ) . (3 1 1))
    ((u x b u x b u u u u u u u u u u ) . (1 1 6))
    ((b x x u u u u u x u x u b u u x u u ) . (1 1 2 1 3 1))
    ((x u u u u u x b u u u u u u x x b ) . (4 1 2 2 1))
    ((x b b x u u u u u u u u ) . (2 1 1 2))
    ((u u b b u b u u b u x b u u x u u ) . (7 1 3 2))
    ((u u u b u u u u u u u b u u u u x ) . (4 5 1))
    ((u u u u x u u u b b u u u x u u u u b ) . (1 1 1 3 2 1))
    ((u u x u b b x u x x u u u u ) . (2 1))
    ((b u u u x u u u u u u b u u u b u u ) . (1 1 7 3))
    ((b u u u b u u x u u ) . (5 1))
    ((b u u x b u u x b x b u u u u b u u u ) . (1 1 1 1 1 7))
    ((u u u u u u u u u x u u u u u u u u ) . (1 1 2 1 1 2))
    ((u u b b u u b u u u u u u u ) . (7 1 1))
    ((b b u u x u u u x u u u u x ) . (4 1 1))
    ((u b u u u u x u u u u u x x x ) . (4 2 1))
    ((u u u u x u u u u x u u u u b u x u ) . (1 5))
    ((u u u u u u u b u u u x u u u u ) . (4 3 1 2))
    ((u u x u u x u x u u ) . (1 1 1))
    ((u u u u u u x u b u u u b u u ) . (3 1 2))
    ((u u x b u x u u b u u u u u ) . (1 1 3 2))
    ((u u b x u u x x u u u b x u u u ) . (1 2 1 1 1))
    ((u u b u u u x u x u ) . (4 1))
    ((u x u u u x x x u b u ) . (1 3))
    ((u u b u b u u b u b u ) . (3 1 1))
    ((u u u x b u b u u x u x x b b u u u ) . (1 1 5 1 2 1))
    ((u x b u u u u u u b b b u ) . (1 1 4 3))
    ((u b b b u u x u u u u u u b u u u ) . (6 1 2 1 1))
    ((u u b u u b u u x u u u b u x u u u ) . (8 3 1))
    ((x u u u u u u u u u u u b u u ) . (2 1 4 1))
    ((u b u u u x x u b b u u ) . (2 3))
    ((u u u u u u u u u b u u x b u ) . (1 1 5 1))
    ((u u u b u u u b u u b u u u u u b u b x ) . (4 12))
    ((u u b u u u u u u u u u u u u u u ) . (6 4 1))
    ((b u u u b b u u u u x u b x u u ) . (1 5 1 2 1))
    ((u b u b u b u b u x u x u u u ) . (9 1))
    ((u x b u b u u u u u u u b u ) . (5 1 3))
    ((x u u u u u u u u b u ) . (3 1 1))
    ((x u u u u u u u u b b b ) . (3 1 3))
    ((u u x u u u x u u u b u u u b u ) . (1 1 2 3))
    ((u u u b x u b b b b u u u x u u u ) . (3 4 1 1))
    ((x u u b x x u u u u u u x u u u ) . (2 4 1))
    ((u u b u b b u u u b u ) . (4 2))
    ((u b x u b u b u u u u u u u u u b ) . (1 5 6))
    ((u u b u u u u u x u u u u u ) . (3 2 2))
    ((u u u u u b u x u u u x u u u u u u ) . (5 2 2 1))
    ((x u b u u u b u u u u b ) . (6 3))
    ((b x u u u u x u u b u u x u ) . (1 4 1 1))
    ((u b u u u x x u b u u u x x u u ) . (5 2 1 1))
    ((u u u u u u b u u x b u x ) . (7 2))
    ((u u u u u u x x u u x ) . (3 2))
    ((u u b u u u x u u u u b u x ) . (2 1 2))
    ((b x u u b u b u u u u u b u ) . (1 7 2))
    ((x u u x b u x u b u x ) . (1 2 2))
    ((u b u u u u u u b u x u u u b u b ) . (3 1 2 1 3))
    ((x u u x x u u u u u u ) . (2 4))
    ((u u u u u u u u u u x b b b b u b u x u ) . (2 5 6))
    ((x u u u u u u u u u u b x b u x u b ) . (1 8 1 1))
    ((u u u u u u b u u b b u b u b b u u ) . (1 2 11))
    ((b b b u u u u b u x u x b ) . (5 2 1))
    ((u u b x x u u x u u u ) . (2 1 1))
    ((b u u x b u u b u b b u u u b u b x ) . (1 1 1 9 1))
    ((b u u u u b x u u x ) . (3 2 1))
    ((u u u u x u u u u x u u u b ) . (1 3 2 1))
    ((b x u b u u u b b u b x x ) . (1 4 4))
    ((x x b u u u b x u u ) . (1 1 1))
    ((u u u x u b u b u u x b u b u x u ) . (1 4 4))
    ((u b u u u b b u u u b b u u u u u u b ) . (7 10))
    ((x u b u u u b u u u x ) . (2 2))
    ((u u u u u u u u u u b u u u u u b u u b ) . (1 1 6 1 1 2))
    ((u u u u u u u u u b x x b b ) . (1 1 3 2))
    ((u u u x u u u u u u u u u x ) . (2 2))
    ((u b u x u u u u b b b u b u ) . (1 1 4 1))
    ((b x x u u u b u u u u u u u u u u b ) . (1 1 1 3 2 1))
    ((u b x u u u u b b u u ) . (1 1 2))
    ((u b u x u x u u b u ) . (3 1 1))
    ((x u u u u u u u u u x ) . (1 4))
    ((u u u u u x b u u u u ) . (2 2 1))
    ((b u u b u x u x u u u u x u x ) . (5 1 1 1 1))
    ((b x u b u u u x u u ) . (1 3 1))
    ((u u b u u u u b u u u b b u u u u ) . (1 1 8 1))
    ((x u x u u u u u b u u ) . (1 1 3))
    ((b u b u b b x u x u u u u u u x x ) . (6 1 1 1 1))
    ((b u u x u u u x u b u u u u ) . (1 1 1 5))
    ((u b x u u u u u b x u b x u u u b b x u ) . (2 6 1 3))
    ((u u u u u x u u u u u u b x u b u ) . (1 6 2))
    ((x u u u u b b u u u u u ) . (6 1))
    ((u u u b u x u b u u b u u b ) . (4 2 4))
    ((u u u u u u x u u b u u x x ) . (1 1 1 3))
    ((u u u u u u u u u u u u u b u u u u u ) . (1 11 3))
    ((x x u x u u u u u x u u ) . (2 1 1))
    ((b x u b u u u u u x u u u u u u b ) . (1 1 2 2 2))
    ((b u u x u u u x x u u u b b ) . (3 1 1 2))
    ((u u u u u b u u u u u x b u u u x b ) . (5 1 1 1 1 1))
    ((u b u b u u x u x u u u b ) . (2 1 1 4))
    ((b b x b u b u x b b b b u u u u x ) . (2 1 2 7))
    ((u b u u u u b b b u u u b u u x u b u x ) . (15 3))
    ((x u u b b u u x u u u b b x ) . (4 5))
    ((u b u x u u u u x u b b u b u ) . (1 3 4))
    ((x u u u u u u x u u x ) . (3 1))
    ((x u b u u u x u b u u u u ) . (2 3 2))
    ((x u u u u u u u x u x x ) . (1 2))
    ((b u b x u u u x u u b u u u ) . (3 2 2 1))
    ((u u u x u u u u u b u u u u u b u u ) . (6 1))
    ((u x u b b u u u u u u x u u x ) . (6 1))
    ((b b b u b b u u u u u u b u u u x ) . (3 2 7))
    ((u u u u b u u u u x u u b u u u u x ) . (8 3 1))
    ((u b u u u u x u u x u u u u ) . (4 2 1 1))
    ((u x u u u u u b u u b u u b u u u b u ) . (4 1 9))
    ((u x u u u u u u u b b u b u x ) . (4 4))
    ((u u b u u u u u u u b u u u b u x u ) . (1 9 1 1 1))
    ((u x b u u u u b u u u u u ) . (1 1 6))
    ((u u u b u u u u u x u u b b ) . (6 3))
    ((u x u u x b u u u u u ) . (1 1 4))
    ((x u u u b u u u x u u x u u u x u u ) . (4 1 1 1 1 1))
    ((x u u u u u x x x u u x x x u u ) . (1 1))
    ((x u u b u u b u u u u u u u u u u u ) . (4 8))
    ((u u u x x u u u b b b u ) . (2 6))
    ((x b u u u x u u u u b u u u x u u ) . (4 2))
    ((u u x x u u x b u u b u u b u ) . (1 7))
    ((u u b u b x u u x u x u u u b b u b x ) . (1 1 1 1 1 7))
    ((b u u u u u u u u u x u b u u u ) . (8 1 1 1))
    ((u u u u u u u u u u u u b u u u ) . (2 8 1 1))
    ((b b u b u b b u u u ) . (2 6))
    ((u u u u x u u x b b u u u u u u b u ) . (1 1 1 2 5))
    ((u u u u u u b u u u u u u ) . (2 3 1))
    ((x u u b x x b b u u u u b u b u u x u ) . (3 10))
    ((u u u x b u b u u u u u b u ) . (1 3 1 2))
    ((u u u u u b u b u u x x u b u u u ) . (2 5 3))
    ((u x u x u u u b u u u ) . (1 4))
    ((u u b b u u u u u u u b u u u ) . (7 1 1))
    ((u u b x x u u b x u u ) . (1 2))
    ((u u u u u b u x x u u u u u u b b ) . (5 7))
    ((u b u u x u u b b u b b u ) . (1 7))
    ((u u u u x x b u u u u x b b u u u x ) . (3 1 1 5))
    ((u u u x u u u u b u x u x u u b x u u ) . (1 2 3 1 1 2))
    ((u u u b b u u u u x x u u b u u u u x ) . (1 6 7))
    ((u u u b u u u u u b b u x u u u u u ) . (1 1 5 4))
    ((x u b u u u x x u u u u b x ) . (1 5))
    ((u u u u u u u u b b u u x b x ) . (2 1 4 1))
    ((u u x b u u u u u x x u u b b b b b u ) . (1 7))
    ((u u u b u x u u x u u u u x u b ) . (2 1 3 1))
    ((u u u u u x u u u b ) . (2 1 4))
    ((u u b u b u u u u b b x x b u u b u u ) . (5 3 1 2))
    ((u b u u u u u b b u u u u u ) . (10 1))
    ((u u b u u b u u u x u x b u u b u u ) . (6 1 1 1 3))
    ((b u x u u b b u u u u b b b b ) . (1 6 4))
    ((u u u b u b u u u u u u b b u ) . (6 4))
    ((u b u u u u u u x x b ) . (6 1 1))
    ((u u u u x u u u b u u ) . (1 1 5))
    ((x b u u b x u u x u u x u u b ) . (4 1 2 3))
    ((u u u b x u x b u x x u b u u u x u u ) . (1 1 1 2 2 1))
    ((u u u x u b b u u b x u x ) . (2 4 1 1))
    ((b x u u u x u u u b u b x u ) . (1 1 5))
    ((u u u u x x b u u u b u b u u ) . (2 1 9))
    ((u x u u u u u x u u u x u ) . (1 1))
    ((b u u b u b x u b u x u u u u b ) . (6 1 3))
    ((u u u x u u b b u x u u x u u x u b u ) . (1 1 4 1 1 3))
    ((u u u u u b b b u b b x u u u u u u u u ) . (1 8 1 1 1))
    ((u u b b u u u u u u b x u ) . (4 3 1))
    ((u u u b x b u u b x u x b u b ) . (4 1 1 3))
    ((u b u b u u u b u u ) . (5 2))
    ((u u u u b u b u u u u u u u u b u u ) . (3 5 1))
    ((u u x b x u u b b b x u u u u u ) . (1 1 4 1 1))
    ((x x u u u b b u u u u u u u b u x u u u ) . (12 1))
    ((b b b u u b x u b x u u u u b u b u b u ) . (6 1 2 3 1))
    ((x u u u b u u u u u u u b u ) . (1 1 1 3))
    ((u b x x u u x u u b u u u b x u u b u ) . (1 7 3))
    ((u x b b x x b u b u b b ) . (1 2 6))
    ((u u x u u u x x u x b u u u u ) . (1 2))
    ((u x u u x x u u b u x x x u ) . (1 3))
    ((x u u u b u u u u b u x u x u u x u u ) . (5 1 2))
    ((x x u b b u u u u u b u u ) . (3 2 3))
    ((u b u b u u u b u b u u ) . (4 4 1))
    ((u u x u u b u u b x x u u u b u b ) . (6 4))
    ((b u u u x u u b u b u b x b u u u u u ) . (2 1 1 5 1 3))
    ((u b u u u u x b u x u u ) . (2 3 1 2))
    ((u b b u b u u u u x ) . (6 1))
    ((x x u u x b u u b u u u x u u ) . (2 1 4 1))
    ((u u u b x u u x u u u u u ) . (3 1 3))
    ((x b u u u u u u u u b u b u u b ) . (5 1 7))
    ((x x u u u u u u u u u u u x b u ) . (1 4 2 1))
    ((u u b x b u u u u u u u u u u u x u ) . (1 1 5 6))
    ((u x b u u u x u u u x ) . (3 2))
    ((b x b x x u u u u u b u u b u u u ) . (1 1 10))
    ((u b u b b u x u b b b b u b u u u u b ) . (4 4 1 1 2))
    ((u x x u u u u u u u u ) . (1 1))
    ((u x b b u b b b b u x u u u b x x u u u ) . (7 1 1 1))
    ((u b u u u x x u u u ) . (2 2))
    ((u x u u x b u u u b u b x x u u u ) . (1 3 1 1 2))
    ((u u x u u u u b u x u b u x u ) . (2 1 1 1 1))
    ((u x b u u u u u b x u b ) . (7 1))
    ((x b u u u u u b u b b u b u ) . (2 4 1))
    ((x u u u b u u u u u u u u u u u b x u ) . (1 5 1 3))
    ((u u u b u b u b u u x u x ) . (7 1 1))
    ((u b b u x b u u u b u u b u x u ) . (3 6 2 1))
    ((u u u u b u u u u u u u x x u u b u ) . (1 1 1 6 4))
    ((u u b b b u u x u b b u u u b x u u ) . (3 7 2))
    ((u u u x x u u u u x u ) . (1 3))
    ((u u u u x u b u x b u ) . (1 2 1))
    ((u x b x b x u u b b u b b u u x u u ) . (1 1 1 1 7 1))
    ((x u b b b x u u u u u u ) . (4 1 1))
    ((u b u u b b x u u u u x u u u u u u u ) . (1 3 2 1 1 4))
    ((x u u u u b b u u u u ) . (1 4))
    ((x b u b b u x b u u u u x u u u b u ) . (4 2 1 4))
    ((x u b u u u u x u u b x x b ) . (4 1 3 1))
    ((u u u u u u u u u u u b b b ) . (1 3 2 4))
    ((b b b u u u b u u u u b u u ) . (4 1 1 1))
    ((u u b b u u u u u u u u b u b u u ) . (3 7))
    ((b u b u b b b b b u b u u u u x u u x ) . (14 2))
    ((u u u x x u u u u u u x u b u b u u u u ) . (2 5))
    ((u u u u b b b u x b b u ) . (5 2))
    ((u u u u u x u b u u u b u u u u b x u ) . (1 10))
    ((b x u u u x u u u b u u u u u u u u u ) . (1 2 1 6 3))
    ((u u b x u u b b b u u u x u u u x ) . (2 4))
    ((u u b u u u u u u u x u u u ) . (4 2 1))
    ((b u x x b u u u b b u b b u u ) . (2 6 4))
    ((u u u u b u x u u x u b x u u x ) . (2 1 1 2 1))
    ((b b u u u u b u u u u u x u x u u u x ) . (8 1 3))
    ((u u b u u x u u u u u x u ) . (3 4))
    ((b u u b u u u u u u u u u x u u u ) . (1 3 3 3 2))
    ((u u u u x u u u u b b u ) . (4 6))
    ((x u u u u b b u b u b u u x u u u ) . (7 1 2))
    ((u x b u x u u u u x u u u b b u ) . (1 1 1 1 4))
    ((u u x b u u u b u u u x u b u u b u ) . (5 1 4))
    ((u u b u b b u u u u u u u u u u u u ) . (10 1 1))
    ((b u u u u u u u x u b b b ) . (2 3 4))
    ((x u u x b u u u u u b u b x b u u b ) . (1 1 3 1 1 4))
    ((x b b u b u u u b x u u u u x b u u b u ) . (8 1 4))
    ((x u u x u u b u u b x u u u b b b u x ) . (1 6 7))
    ((u x u u b u b u x u u u ) . (1 1 3 1))
    ((u u u b u u b u u u ) . (1 5 1))
    ((x u u x x b u u u b u ) . (1 3))
    ((u u u b u b b b u b u b x u b u u b ) . (12 2 1))
    ((u u u u b x u b b u u u ) . (5 4))
    ((x b b u x u u x b b b u x b u u b ) . (2 1 3 1 1))
    ((u u x u u b b u u b u u u u x b x u ) . (1 7 1 1 1 1))
    ((u b u u b x u u x b u u u u u u x b u u ) . (5 1 1 1 1 1))
    ((x x u u b b b x u u u b b b b u x u u u ) . (5 6))
    ((u u u u b u b u b x u u b ) . (6 1 1 1))
    ((u u b u b u u x b u b x u ) . (3 3))
    ((u u b b u b u u u u x ) . (3 1 2))
    ((x u u b u u x b x u u u u u u u x x ) . (5 1 2))
    ((x b u u u u u u u b u ) . (1 1))
    ((b b u u u u u u u b b u u u ) . (2 10))
    ((u u u u x b u u u u b u u u u u x u ) . (2 1 2 1 4))
    ((u u u b b u u u u u b u u u u b u ) . (1 2 1 4 3))
    ((u x b u x u u u u b u u u b u x ) . (1 1 1 4 1))
    ((x u u u u x u u u u u u ) . (2 2))
    ((u u x b u b b u u u u u u ) . (2 6 1))
    ((x u b u x b u u u u u u b u u b ) . (2 5 4))
    ((u b u u x u u u u u u u u u u b b ) . (1 1 8))
    ((u u u u u u u u b u b ) . (1 8))
    ((b u u u b x u u u u b ) . (3 1 3))
    ((u u u u u u u x x u u b u b u u u x ) . (1 6))
    ((u u x u u u x b x u u u u u b u u u x x ) . (1 1 1 3 4))
    ((u u u b u b b u u u b u u u u b x b x ) . (9 2 1))
    ((x x x u u u u u u u u ) . (4 1))
    ((u u u b u b u u u b u u b u x u u u ) . (10 1 2))
    ((x b b u x u u x u x ) . (3 1))
    ((u u u u u u u b u u u ) . (1 3))
    ((u u u b b u u u u x u ) . (7 1))
    ((u u b u u u u u b b u b u u x x ) . (2 4 1))
    ((u u u x u u u u b u u u u ) . (1 6))
    ((u u b u u u b x u u b u u ) . (7 1 1))
    ((u u u u u b b x u u x u u u ) . (7 1 1))
    ((u b u u x u b u u x x ) . (2 2))
    ((u u b u b u u u u u b u u x b u ) . (1 1 1 4 2))
    ((u u b u u u b b u u b b u u u u x u u ) . (2 9 1 1))
    ((u u u b b u u u u u u u u u u x b x u u ) . (6 1 3 1 1 1))
    ((b u u u u b u u u u u u u u u ) . (1 1 8 1))
    ((u u b u x u u b x u u u ) . (1 3 1 1))
    ((u b b u u b x u u u ) . (3 1))
    ((u x x b u u u u u u u ) . (1 3))
    ((x x u u b b x x u b u b b b x u ) . (4 6))
    ((u u b u u u u u u u u x u u u u ) . (6 1 2 1 1))
    ((u x u u u u u x u u u ) . (1 3))
    ((u b u b x b u u u b x b u ) . (3 5 2))
    ((x u x u u u u b u u x ) . (1 1 2))
    ((u u u x u u u x u u b u x ) . (2 1))
    ((u u u u b u u u u u u b u u u u b u ) . (1 1 1 5 1 1))
    ((b u u u u u u b u u u b x u u u u ) . (12 2))
    ((x u u u u u u u u u u u u b u u x u x ) . (6 2 3 1))
    ((u u u x u u b b b u u x u u u u u b u ) . (3 6 2 1))
    ((u x u b u u b u u x ) . (1 1))
    ((b u u b u b u u u u b b ) . (4 1 4))
    ((u x u u b u u u u u b u u u u u x ) . (4 6))
    ((u u b u u u u x b u ) . (1 2 1))
    ((u x u u b b x u b b u u u b u u ) . (1 3 4 1))
    ((u b u u u u u u b u u u b u x b ) . (1 1 3 1 1))
    ((u u u b x u u u u u u x u u u ) . (1 1 1 1 2))
    ((x u u u u x b u u u u ) . (2 4))
    ((b b u u b u x x u b b x u u u u x x x u ) . (6 3 1 2 1))
    ((u x b u u b u u u x x b b u u u ) . (1 2 4 5))
    ((u u u b u u u u u x u u u b u u b u ) . (1 3 2 4 2))
    ((x u x b u u u b u u u x u u x b ) . (1 6 1 1 1))
    ((b u u u b u u u u x x b b u u u u u u ) . (9 2 4))
    ((x b u x u u u u u u u x b u u b b b u x ) . (2 5 6))
    ((u x u b b b u u u u u ) . (1 4 1))
    ((u u u u b u b b u u u u u b x u ) . (1 6 4 1))
    ((u u x u u x u u u u b b u x u ) . (1 1 2 3))
    ((u u u u b b b u x x u u u u u ) . (6 3))
    ((x u u u u u x x u u b u u u x x x ) . (3 4 1))
    ((x u x b u b b u b b u u u u u u u u u ) . (7 1 4))
    ((u x u b b b u u u b u u x u u x u ) . (1 8 1 1 1))
    ((u b u b u b b u b u u u x u x u u u u u ) . (9 2 1 1 1))
    ((u x x u u b u u u u x u u u u x u b ) . (1 3 3 3 1))
    ((u u u u b b u x u u b u x x u u u ) . (6 3 1))
    ((x u u x u b b u x b b u x u ) . (1 4 3 1))
    ((u u b b u u u b u u b u u u x u u ) . (1 3 6 1))
    ((b u u b u u u x u u x u ) . (7 1 1))
    ((u x x u u x u x u u u x x ) . (2 3))
    ((u u u u u u b u u u u u b x ) . (2 4 1 1))
    ((u u u x u u u u u u x b x u u ) . (1 1 2 1 1))
    ((u x u b u x u u u u u ) . (1 2))
    ((x b x u b u u b u u u u u u u u ) . (1 4 2 1))
    ((u u x x u u u b x u x ) . (1 1 2))
    ((u x u u b u u u x u u u u u ) . (1 6 1 2))
    ((u u b x u u u b u u u b u u u ) . (2 8))
    ((u b b x x u b x b u u u u u u u b ) . (3 1 3 5))
    ((u u x u u b u b u u ) . (2 4 1))
    ((x b u u x u x x u u u ) . (3 1))
    ((x b u b u x u u u u u u u u ) . (3 2 1 1))
    ((x u u u u u u b u b u u b ) . (4 1 1 1))
    ((u u u b u u u u u x u u b u u u ) . (3 1 6))
    ((u x b u x u b x u u u ) . (1 2 1))
    ((x u b u u b b u u b ) . (1 5))
    ((u x x u u u u b u u ) . (1 3))
    ((u u u u u u u u u b u b x u u u u b b u ) . (3 2 1 1 1 4))
    ((x x b x x u u u b u b b u ) . (1 1 4))
    ((u u u b b u u x u u b u b b u u u u b ) . (1 3 1 4 1))
    ((u u u u b u u b u b b b b u u u u u u ) . (2 10 1))
    ((u u x u u x b b x x u u x ) . (1 1 2 1))
    ((u u x u u u x u u u b b u b u b b x u x ) . (1 1 1 10 1))
    ((u u u x u u u u u u u u u ) . (2 1 2))
    ((x u b b u x u b u u u u u b u u x u ) . (3 8))
    ((b u u b u u u x u x u b x u ) . (4 2 2 1))
    ((u u b b b b u b b u u u u b u u ) . (9 4))
    ((u u u u u b u u x u u x x x u x u x x u ) . (2 1))
    ((u u u u u u u x u b u u ) . (2 1 2))
    ((u u x b u u u u u u u x u u b x x u b ) . (2 3 3 2 2))
    ((u x x u u u u u u u u u u u u ) . (1 1 3 2))
    ((u b b u u u u x u x u b x u b u u u u ) . (5 1 1 1 1 1))
    ((x u u u u x u u u u u u u u u x u x ) . (4 1 4))
    ((u u u u u u u u b u u u u ) . (1 1 4))
    ((b u b b u b x u u x u b u u u u u u u b ) . (6 1 1 1 1 1))
    ((u u b u u u b b u b u u u b ) . (1 1 7 1))
    ((x u u b u u u u u u u u ) . (3 1))
    ((u u u u u b u b b b u u b b u ) . (2 9))
    ((u x b u b u u u b b u u b u u u u b ) . (1 1 1 1 6 2))
    ((u u u u b u x x u b b x u u u ) . (2 2 3 1))
    ((u u u x u u u x u u x u ) . (3 1))
    ((b u b x b u b b b u u x u u u u b b u ) . (1 1 5 1 2 3))
    ((u u u u u u u b u b u u u ) . (10 1))
    ((x u u u u u u u u u x ) . (1 1))
    ((x x b x u b b u u u u b b ) . (1 5 3))
    ((u u u b u u u u u x u u ) . (1 2 1 2))
    ((u u u u x u u b u u b ) . (1 6))
    ((u u u u x u u b b u u u u u u x ) . (4 6 2))
    ((u u x u u u u b x u x u b u b u u u ) . (5 5))
    ((u x u u u b x u u u ) . (1 1 2))
    ((b x u x u b x x u b b b u u u b u u u ) . (1 1 2 5 1 1))
    ((x u u b b x x b u x u b u x ) . (4 2 1))
    ((u u u x u b u x u u x u x ) . (3 1))
    ((u b u u u b u x u b u x ) . (3 1 2))
    ((u x u u u u b u u u ) . (4 2))
    ((u u u u x u u b u x x u u u b u x ) . (3 3 1 2))
    ((x x u b b u u x x u b u u u u u b u b x ) . (4 10))
    ((u u b u x u b u u b ) . (3 1 1))
    ((b u x u u u x b u b u u u b b u u ) . (1 1 3 5))
    ((u b u u u b b u b u u x u u u b u x ) . (8 4))
    ((u b u x u b u x u u u x u b ) . (1 3 1 2))
    ((u u u x u u x u u u u u u x b x u u ) . (1 1 3 1 1 1))
    ((x u u b u u u u u u b u x u u ) . (6 2))
    ((u u u u u u u u u x ) . (3 2))
    ((u u u u b u u x u u u u b u ) . (2 2 1 1))
    ((u u b u u u u b u u u x u u u ) . (4 2 1))
    ((b b u u u u u b u u u ) . (4 1 1))
    ((x b u u x u u b x b x u ) . (2 2 1))
    ((u x u b b u u u u u ) . (1 5 1))
    ((b u u u b u u b u u u u u u u x ) . (2 4 4 1))
    ((u b u x u u u b b u u u u b u u u ) . (1 9))
    ((b b u x b u u x u u b x x u b u u u u x ) . (3 3 1 1 5))
    ((u b x u u u b b b b b u u u b u u b u u ) . (1 8 1 1 4))
    ((u u u b x x u u u u x b u u u u u ) . (3 1 6))
    ((u x u u u u u b b u u ) . (1 2 2))
    ((u u u b u b u u u u x x b u u u u x ) . (4 2 4))
    ((x x u u u u u u x u u u u u b x u u ) . (3 1 1 1 1 1))
    ((b b u u b u u u u u u u u u u b u u x b ) . (2 1 10 1))
    ((u x b u b b u u u x u u u ) . (1 5 1 2))
    ((u x u b x u u u u u u u u u u b u u b x ) . (1 2 10 1))
    ((u u u x u b u b b x u u x u b u b u u u ) . (3 5 2 1 3))
    ((u u x x b x u u u b ) . (2 1 4))
    ((u u x u u u u b b u b u b u u u u ) . (1 6 2))
    ((u x u x u u u b u u u u x u u x u ) . (1 4 1 1 1))
    ((x b u u x b u u x b u x u u ) . (1 3 1 1))
    ((x u b b u b u u u x u x x ) . (3 1 1 1))
    ((u b u u u u u u u u b u u b u u u ) . (1 1 10 1))
    ((u x u u b u u x x b x ) . (1 2 1))
    ((x u b u u u u b b u u u ) . (4 2))
    ((x x b x u u u x u b u u u u u u u u b ) . (1 2 11))
    ((u b b u u b u x u u u u x u b u u x ) . (6 2 3))
    ((u u u u x x u x x u u b u u x b u b ) . (1 1 1 1 1 3))
    ((u u u u b u x b x u ) . (3 1))
    ((x u u b u u x u u x x ) . (3 1))
    ((x b u u b u u u b u u u x ) . (5 4))
    ((u x u x x b u u x u ) . (1 1 1))
    ((u u b x x u u u b u x x ) . (2 4))
    ((b b u u u u u u u b u u u u b b u x u ) . (3 2 4 3))
    ((u u u b u u u u x b u u u u x u u ) . (4 3))
    ((u u u u u b b b b u u u u u u u u u b u ) . (14 1))
    ((u u u u u b x u u b u u b ) . (3 1 5))
    ((x u x u b u u u b u u b b u u u ) . (6 4))
    ((b u u u b u u x u x x u u b b u b u u u ) . (7 1 9))
    ((u u u u u b u u u u u u u b u u u ) . (3 2 1 6))
    ((u u u b b b u b u u u u b u u b x u b ) . (5 9 2))
    ((u u u b u u x u b u u b u b u u u b ) . (4 7 2))
    ((x x u u x x u x b u u u u u u b ) . (2 1 1 5))
    ((x u u u u u u u u b u u u ) . (1 3 1 1))
    ((u u u u x u u b u b u u u u ) . (2 4 1))
    ((x u u u u u u u u u u u x ) . (2 3))
    ((u u u u u u b u u u ) . (4 1 1))
    ((u u u u u x u u x u u x u b u ) . (1 1 1 1 2))
    ((x b u u u b u u u x u u u u x u x u ) . (8 2))
    ((x u u b x u u u u u u x x u u u u u u u ) . (1 1 1 4 2 3))
    ((u u u u u u x u u u u ) . (3 2 1))
    ((b u x b u u u u u x u u u u u u ) . (1 1 1 2 2))
    ((u u b x u u b x x b b u u u ) . (2 2 3 1))
    ((u b u u u x u u u u ) . (4 4))
    ((u u u x u u u u u x b u u ) . (2 3 1))
    ((u u b u x b u b u u b b u b u u b x ) . (1 12))
    ((u x b u b b u u x u u u u u u x ) . (1 1 4 1 4))
    ((x u x u u b u u u u u u b b u u x b ) . (1 12 1))
    ((x x b u u u u u u x b u u x u u u ) . (3 2))
    ((u u u u u u u x u u u u u b u u u x u x ) . (1 3 7 1))
    ((u b u x u u u u u b u x u x u ) . (1 1 1 2 1))
    ((b u u u u u b u u u x u u u u u u ) . (8 1 1 1))
    ((u u u u u u u u b u u u b u u b ) . (1 1 1 2 6))
    ((u u u u u u b u u u x u b u u u u b b b ) . (4 1 9))
    ((u u b u u u u u b u u u u u b u b u ) . (3 10))
    ((x u u b b u u u x u u ) . (4 1))
    ((u u u u b u u u b u ) . (1 2 3))
    ((u u b u x u b u u u u u ) . (2 6))
    ((b u b u b u x x u x b u u u u ) . (5 1 1 2))
    ((u u x u u u u u b u u u u u u b u u b ) . (2 1 5 1 4))
    ((x b b u u x u u x x u u u b x u ) . (2 2 4))
    ((u u b u u u x b x u u ) . (4 1 1))
    ((x b u u b u u u x u b x x u x u u x u b ) . (5 1 2 1 2 1))
    ((u b u u u u u b b u b u u u u x u x ) . (4 7 1))
    ((b b u u u u b u u u b u u u x ) . (4 1 3))
    ((u x u u u u u u b u u x u u u u u x u ) . (7 5))
    ((u u u u u b x u u u x u ) . (1 1 2 1))
    ((x b u u u u b u b u u b b u b x ) . (1 2 4 4))
    ((u x u u x u u u u b b u ) . (1 1 1 3))
    ((u b x b u u x u b u u u ) . (2 1 2 1))
    ((x u u u u b u u u u u u b b b u u x ) . (8 5))
    ((x u u u u u u x u b u ) . (1 1 2))
    ((u b u u u u u u u u u ) . (4 1))
    ((u u u b x u u u b x b b u u b b u u b ) . (1 2 1 1 9))
    ((b u u x x u u u u u u ) . (3 3))
    ((u b b u u u x b u b u u u u u b b ) . (5 6 3))
    ((u u u u u b u u b x u u b b u u u x ) . (1 2 2 4 2))
    ((x u u u b u u u u u b u u u b b u u ) . (5 1 1 3 1))
    ((x x u x u x u b u u b u u u u b x u ) . (1 1 2 3 1 1))
    ((u u u u u b u u u u u ) . (2 3 1))
    ((u u b u u u u u u x u u u x x u ) . (1 2 1 2 1))
    ((u u u u u x u x x u b b u b u u u u u ) . (1 3 1 7 1))
    ((u b u x u u x u b u b u u b x u u ) . (3 1 4 2 1))
    ((u u u u x u u b u b u b u ) . (1 1 6))
    ((x u b u u u b u u x b x u ) . (2 2 1))
    ((u u u u x b u u u u u x ) . (2 2 1))
    ((u x b u u x x u u u u u u b u u u ) . (2 10))
    ((u b u x u u b u x u x u u ) . (3 3 1))
    ((x u u b u b u u b u b u b b u u u u u b ) . (1 12 3))
    ((x u x x x u b u b u u b x ) . (4 1))
    ((x u b u u u u u u u b u x u b u u b u ) . (2 1 3 2 2))
    ((x u x u u u x u u u u u ) . (1 1 3))
    ((u u u b u u u x x b ) . (3 1 1))
    ((u u u u x u u u u u b u u ) . (3 1 2))
    ((b x u u b b u u u u u u u u u b u ) . (1 5 3 1))
    ((u u b u u u u u u u u u u u ) . (4 5 1))
    ((u u u u u u x x x x b b u u u b u ) . (1 1 1 3 2))
    ((u u x u u u u b b u u u u u x ) . (1 10))
    ((u u u u b u u u u u b u u ) . (1 4 1))
    ((u u u u u b b u b u ) . (1 2 1))
    ((u b x b u b u x u b x u x x b u b b b ) . (1 3 1 1 5))
    ((u u x b u u x u u u b u b u b u b u u u ) . (1 1 11 1))
    ((u u b u b u u u u b u b u ) . (1 1 2 4))
    ((u u b b u x u u u u ) . (2 2))
    ((u x u u u b u u u u u x u u u u b u b ) . (1 1 5 1 2 3))
    ((b b u u u b u u u b u u ) . (4 6))
    ((u u b u u x u u u u u u u x x u ) . (1 3 2 1 1))
    ((u u x u b b x b b b u u u u u u x x x u ) . (1 3 5 1 1))
    ((x u u u x u b b u u b ) . (1 4 1))
    ((u u u u u u x b x u u b b u b b u b u ) . (2 1 1 1 9))
    ((u u u u u u u u u b b u u u u x u u ) . (11 1))
    ((b u u b u b b u u u u b u b u ) . (1 11))
    ((x u u b u x u u x u u ) . (4 1))
    ((u b u u u u x u u x u u u b ) . (3 2))
    ((x u x u u u x u u u ) . (1 2 1))
    ((u u b b u u b u u b u u b u b u u b x ) . (1 2 2 1 4 1))
    ((u u u x u u b u b u u b ) . (1 1 4))
    ((u x b u u u b u u b b x u u x x u u u x ) . (1 6 2 1 1 1))
    ((u u u b u u u u u x ) . (3 3))
    ((u x u u u u x u x b u ) . (4 1))
    ((u u u x b u x u b u u x x b u u ) . (1 2 2 3))
    ((u u b u u u u u u b b x ) . (1 6 2))
    ((u u b b u b u u b b u ) . (5 3))
    ((u u u u u u u u x u b u ) . (3 3 3))
    ((x u u u u u u u u u u x u b b u u u ) . (8 4))
    ((u u x u u x u u b b u u u b b u x ) . (2 2 9))
    ((b u b u u u x x u b b b u x u u u b u ) . (5 3 3))
    ((u u u u u x x u b u u b u b b u b u u u ) . (1 1 2 9))
    ((x u u u b u u x x u ) . (1 3))
    ((u u x b b u u u b u u u x u u u ) . (1 8 1 1))
    ((u x u u u u x u b u ) . (2 2))
    ((u u u b u u u b u u u u b b u u ) . (1 12))
    ((u u u u x u b u b b u x u u u u b b u u ) . (2 2 3 1 6))
    ((u u b u x u x u u u u u u x u u ) . (1 4))
    ((u u u u x x u u x u u u u ) . (1 1 1 2))
    ((u x b u u u u u u b ) . (1 1 2))
    ((u u u b u u u u x u x b u u ) . (1 4 1 2))
    ((u u u b u u u b u u u ) . (5 1 1))
    ((u u b u u u u u b u u u u u x ) . (9 2))
    ((u u u b b u b u u b u u u u u u u u u ) . (7 1 7))
    ((u u b b u u x x u u u u b u u b u ) . (3 1 8))
    ((b u u u u u b u u b u u u x u b u u u x ) . (2 2 5 4))
    ((u b u b u u u u b b b ) . (1 8))
    ((u x x u b u u u u x u u u x u ) . (1 1 2 1 1))
    ((u u u u u u b u x u x x u ) . (1 3))
    ((x u b x u u u b u u b u u u u u x b x ) . (2 10 1))
    ((x u x u b u x u u b u x x u b x ) . (1 2 3 2))
    ((u b u x u u x u u b u u x u u b u ) . (1 1 3 1 3))
    ((x b u u u u u u b u b u u u b x u u u b ) . (2 3 4 1 2 1))
    ((u u u u u u u u x u u u ) . (2 2 3))
    ((u u u u u u x x b b u u u x u u u x ) . (2 3 3 3))
    ((b x u x u u x u u x u u ) . (1 2 1 1))
    ((b u u u u b x u u u b b ) . (1 3 5))
    ((b u u b b b b u x u b u u b b u u u u ) . (2 4 9))
    ((u b u u u u u u x u b u u ) . (2 3 1))
    ((x x x x u u u u u x u x u u u b u u x ) . (1 3))
    ((u u u u x u b u u u x ) . (1 2))
    ((u u b x b u u b b b u b b u b u u ) . (2 13))
    ((x u x u u u u u u u u x ) . (1 7))
    ((u u u u u x u u u u x ) . (1 1))
    ((u x x u b u b u u x u u x u ) . (4 2))
    ((x u u b u u u u u b u b u b u u u u u x ) . (1 2 6 1 1 1))
    ((u b x x b u u x u b x u u u u u u ) . (1 2 2 5))
    ((u x u u u x u u b b u x b u ) . (2 1 2 1))
    ((u u b u b x u u u x ) . (4 2))
    ((u b u u u u u b b b u b u ) . (1 3 3 2))
    ((u u u b x b x b x b u u u u u u b b ) . (1 1 1 1 4 3))
    ((x u b x x u u u u x x u u u b b u u ) . (1 3 6))
    ((u u x b x u b u x b b u ) . (1 1 2 3))
    ((b b u b u u x u u u b x x u x ) . (6 1 1 1))
    ((u u u u u u u x u u ) . (3 1))
    ((u u u b u u u u u u u u ) . (1 1 1 1))
    ((x u u u u b u u u u x u u b u u u u u x ) . (4 7))
    ((u u u u u u u u b b x u x u u u u u x ) . (9 4))
    ((u b b b u x b u u u ) . (4 1 1))
    ((u u b b u b u u u b ) . (6 2))
    ((x u b b u u u u u u u u b x u ) . (2 4))
    ((u u u u x u u u u b u u b u u ) . (2 1 8))
    ((u u u u b b u u b u b u x u x u u b x u ) . (12 1 1 1))
    ((u u u u u x x u u b b u ) . (5 1 2))
    ((u u u u u u u u b u ) . (1 1 3))
    ((u u u u u b u x x u u u x u u u ) . (2 2))
    ((x b u u u u u b u u b u u b u b ) . (5 1 1 1 1))
    ((u b u x u u x u b u u u b ) . (1 1 2 1))
    ((x u u b u b u b u u u u u b ) . (5 1 2 1))
    ((x u b u u x u u u u u u x x u u u ) . (3 2 2))
    ((u u u b b u x b u b x u u u x ) . (5 3 1 1))
    ((b u b u u u u u u u u u x x ) . (4 1 2))
    ((u u u x x u u u x u u b u u b ) . (1 1 1 1 2))
    ((u u u u u u b u u b b u u u x u u u ) . (11 1 1 1))
    ((x x x u u u b u u u u u b b u b u b u ) . (1 1 2 6))
    ((x b u b b b u u x u x u u x u x u b b u ) . (7 1 2))
    ((x u u u u b u b u u x u ) . (6 1))
    ((x u u x u u x u u x ) . (2 1))
    ((u u u u u x b u u u u u u x u ) . (2 5))
    ((x u u u u u x u u u ) . (1 1 2))
    ((u u b u u u x b b x u u u ) . (6 2 2))
    ((u u u b u u x x u b b u u b b u ) . (5 3 4))
    ((u b u u u b u u b u ) . (1 5))
    ((b u b u u u u u b u x u u ) . (1 1 4 1))
    ((u u u x u b u u u u u ) . (1 7))
    ((u u u u u u u x u x ) . (2 3))
    ((u b b b b u u b u u u u u u u u u u b ) . (11 1 1 1))
    ((x u b u b u u u u u u u b u u u ) . (3 1 4))
    ((u u u b u u u u u u u u u b u x x x x ) . (8 1))
    ((u u u u u u u u b u u u u u b u u u u u ) . (2 2 11 1))
    ((x b b u u u b x u u u u u b u b ) . (3 1 4 1 1))
    ((u u b u u u b u u b x ) . (1 3 1))
    ((u u u u u u u u b x u b b b u ) . (3 1 1 4))
    ((u b x u u x u u u b u u u u u u u b u ) . (1 2 1 5 2))
    ((x u u x x b u u u b u u b u b b u u u x ) . (1 14))
    ((u b b u u b u b u x u x x u ) . (6 1 1))
    ((u x x b u u x b x u b ) . (1 1 1))
    ((u x b u u u u u u u b u u u ) . (1 6 1 1))
    ((u u b u x b u u u u u u ) . (1 7))
    ((u u x b u u u u u u x ) . (1 1))
    ((b u u x u u b b x u u u ) . (1 1 4 2))
    ((u u u u u u u u u u x u ) . (1 3 1 1))
    ((b u u u u u b u u u x ) . (5 4))
    ((x u b b u b u u x u b b x u u ) . (3 1 1 3 1))
    ((x u u u b x u u u b u u ) . (1 1 1 1))
    ((x x b b b x u u u u u u x u ) . (3 2 1 1))
    ((u x u u x u b u u u u b x u u b u b u u ) . (1 1 1 4 1 3))
    ((u u u u b u u u u u u u u u u u ) . (3 1 2 1 4))
    ((x u x u u u u u u u ) . (3 1))
    ((u b b b u u u b x u x u u ) . (5 1 1 1))
    ((u u b b b u u u x u x u b u u u x ) . (4 3))
    ((u u x x u u u u x u x u b ) . (1 1 1 1))
    ((b u u x u u x x u x ) . (3 1))
    ((u u u b u b u u b u u u u u u u ) . (8 2))
    ((b u u u u u b x u u u u u u ) . (5 1 2 1))
    ((u u x u b u u b u u u b u u u b x b u ) . (2 13 1))
    ((u u u b u b u b u x b b b u u u u u u u ) . (4 1 8))
    ((u u u x x u x u u u b x x u x b u u ) . (2 4 1))
    ((u u u x u u u b x x ) . (3 3))
    ((u u u u b u b x u u u u b u x x u u u ) . (1 4 1 3 2))
    ((u x u b b b x u u u b ) . (3 3))
    ((u b u b x u x u b u u u b u u x ) . (2 1 1 2 5))
    ((u u u b b u u u b u b x u ) . (5 3))
    ((b u b b u u u b x x u u u b b b x u u u ) . (8 1 3 1 1))
    ((u u x u u b u u u u b u u x u ) . (1 1 4))
    ((b u u b u u u x x u u u x ) . (4 3))
    ((u u b u u u u u u u b u u b u b x ) . (1 12))
    ((u u u b u u b u u b u u ) . (1 2 1 4))
    ((b b b b x u u u b u u b u u u u u ) . (4 1 1 4))
    ((u u u u u b b u u u u u u u ) . (9 1))
    ((u x u u u u u u u u u u b u b u u ) . (3 10))
    ((u u x x u u b u b u b b x u u u ) . (1 1 6 1))
    ((u b u b u u b u b b u b u x x u b u u ) . (6 5 4))
    ((u u x u u x u u b u b u ) . (1 1 6))
    ((u u b u u u b x u u b b u u b x u b x u ) . (1 1 2 6 1 1))
    ((u b u u u b u u u u ) . (1 6))
    ((u u u x b b b u u u u u b u u b u u u ) . (1 9 4))
    ((b u x u u u u b u u u u u u b b b u x ) . (1 1 3 1 4))
    ((u u u x u u b b b x u x b u u u u u x ) . (2 5 1 1 2))
    ((b b u u b b u x u b u u u u ) . (6 1 3))
    ((u u u b u u u u u u x ) . (4 1))
    ((u u u u b u b b b b u b u x u u u u b u ) . (13 1 3))
    ((u u b x u u u u u u ) . (1 4))
    ((u b u b b b u u b x u b u u u u u u u u ) . (6 2 5 1 1))
    ((u u u u x u u u b u u u u u u u ) . (1 2 6 1 1))
    ((b u u u b b u u u u u b b b u u x u x x ) . (8 5 1 1))
    ((u u u b u u u u b x u u u u u x b u u ) . (1 4 1 5 1 1))
    ((u u x x x u b u u u ) . (2 1 1))
    ((u u u u u u u u u u ) . (2 2 1))
    ((x u x u u b u u x x u u b u u u b ) . (1 4 5))
    ((u b u x u u u u u u u u u ) . (3 2 3 1))
    ((u u u u u x u b b b b b u u b u x ) . (5 8))
    ((u b u x u u u b u u b u x u u u ) . (1 1 2 2 1))
    ((x u u u x x u b u b u b b u b ) . (2 8))
    ((u b u u u u u u u u b u u u u u x b u u ) . (2 1 8 1 1 1))
    ((u u u b u u u u x b b u u u x u ) . (2 2))
    ((u x u u x u x u u u u u u u u u ) . (1 7))
    ((u u u u u b u u b x u u u b ) . (1 4 2 1))
    ((u b u u u u u u u x u x u ) . (1 1))
    ((u u u u b b u u x x u u x x x u u u u u ) . (7 3))
    ((u u u x u u u u u u u u u b x x x u u ) . (3 1))
    ((u b u b u u b u u u u u b u b u ) . (9 3))
    ((u u u u u u u u u u x ) . (3 5))
    ((u u b u u x b u u b ) . (4 1 1))
    ((u u u u u u u x u b ) . (2 1))
    ((u u u u u u u b b b u x x u b u u ) . (2 6 4))
    ((u u b u u u u u b b u x ) . (4 4))
    ((x u u b u u u u u u u x ) . (3 1 1))
    ((u x u x x u u u b u u b u ) . (1 1 3 2))
    ((u u u u x x x u u u u b u u b u u u u ) . (1 7))
    ((u u u u u u u u u u u b u u u u b u u ) . (2 1 11 1))
    ((x u u u u u u u u x u ) . (3 1))
    ((u x u u b u u u x u u u u u u u x u u u ) . (1 5 2 1 3))
    ((u b u u u u x x u u u u u ) . (2 1 4))
    ((u u u u u u b u u u ) . (1 1 1))
    ((u x u x u u x u u b u x ) . (1 1))
    ((u u u u u u u u b u u u ) . (4 3))
    ((u b b b b u u u u u b u u u u u u u u u ) . (5 1 1 1 6))
    ((u u u x u x u b u u u b u u b u ) . (1 1 7 2))
    ((x u u u u b b x u u u u u u u b x ) . (4 6))
    ((x u u u u u u u u b b u ) . (5 3))
    ((u u u u u x u u u b u u u ) . (4 3))
    ((u u u b u b u u x x b u u u u x u x u ) . (8 1 2 1))
    ((x u u u u b u x u u b b u ) . (2 2))
    ((u u u u u u x b u u u u u u u b b u ) . (1 1 1 7))
    ((u b u u b u b u u x u u b u u u ) . (1 1 2 1 3))
    ((x u b u u u u x u u ) . (1 1 1))
    ((u x b u u b u u u u u u u u b b u u u ) . (1 16))
    ((b b u u u u u u u u u u u u u b x x u ) . (8 1 1 1))
    ((u x b u b u u u u u u b b x u b u u ) . (11 1))
    ((b u u u u u b x b u b u u u ) . (1 3 4))
    ((u u u u u u u u u u x ) . (1 1 1))
    ((b x u u u u x u b x u u x u x u ) . (1 3 1 1 1))
    ((u b u u u b u u x x x u ) . (3 3))
    ((u u u u u u u b u u u u u ) . (3 1 1 3))
    ((u b b u b u u x u u u u ) . (6 3))
    ((u x u u b u x u u u u u u x b u u u ) . (1 3 5 4))
    ((u u b u x u u u x b u u b u ) . (2 2 5))
    ((u b u u u b u u u b x u ) . (1 5))
    ((u u u b b u b u u u u u u u u ) . (7 5))
    ((b x u u u u x u u u u u u ) . (1 2 1 1))
    ((u u u b x x u u u b b u u b u x b u ) . (1 1 1 2 2 1))
    ((b u b b u u u x x u u u u u u b u b ) . (4 1 1 6))
    ((u b u u x b u x u b u u u x u ) . (1 1 1 4 1))
    ((u u u u x x u u u u b b b u ) . (4 2 4))
    ((x u b u u b b u u b u u u ) . (1 5 1))
    ((x b x u x u b b u u u u u ) . (1 1 2 1))
    ((u u x u x u u u u b u u u u u u ) . (1 1 10))
    ((u u u b b u b u u u u u u x b u u u x u ) . (5 2 1 4 1))
    ((u u x x u u u b x u u u u x b ) . (1 4 1 1 1))
    ((u u u b b u u u u u u x u u u x ) . (2 2 2))
    ((b u u u x u u u u u b u ) . (4 1 2))
    ((b b u b u x u b b u ) . (4 2))
    ((u u u u b u u u u u u u ) . (4 1))
    ((u x u x u u u x u u ) . (1 1 1))
    ((u u x u u u u x x x u u x ) . (1 2 1 1))
    ((u u u u u u u x u b ) . (2 2 1))
    ((u u u u u u u u u x ) . (3 3))
    ((u b u b u u b u b u u u u u x u u x ) . (6 5 2))
    ((b u u u u u u u b u u u b u b b u u u u ) . (2 6 6 1))
    ((x u b u b x b x u u b u u u u u b b ) . (3 1 2 2 2))
    ((x x u b b u u u u u b b u x u u b x ) . (10 2))
    ((u x x u b u u u u u u u u u u u u ) . (1 6 2 1))
    ((u b u b u u u x u u u x u b u u b u u x ) . (2 4 1 6))
    ((u u u x u u u u u u x u u u u x x x u x ) . (3 3))
    ((u u u b u x u u u u u u u b u u u ) . (1 1 1 3 5))
    ((u u b b b u u b b x u u u u u u u u u x ) . (7 6))
    ((x u u u u u u u u x u u ) . (4 1 1))
    ((b u u u u x u b u b b u u b u x ) . (5 8))
    ((u b u u u u u u b u x x u ) . (4 1 1 1))
    ((u u b u b u u u u x u b b u u u u u ) . (1 5 5 1))))

(printf "~a~n" (solve INPUT 1))
(printf "~a~n" (solve INPUT 5))
