;; Input is a list of lists of lists, each representing a 2D map of rocks and soot.
(define EXAMPLE
  '(((r s r r s s r r s)
     (s s r s r r s r s)
     (r r s s s s s s r)
     (r r s s s s s s r)
     (s s r s r r s r s)
     (s s r r s s r r s)
     (r s r s r r s r s))
    ((r s s s r r s s r)
     (r s s s s r s s r)
     (s s r r s s r r r)
     (r r r r r s r r s)
     (r r r r r s r r s)
     (s s r r s s r r r)
     (r s s s s r s s r))))

;; Produces a pair of left and right parts of ls, split at index x. The left part is reversed.
(define split-at
  (lambda (ls x)
    (let f ([curr ls] [i 0] [l '()])
      (if (= i x)
          (values l curr)
          (f (cdr curr) (+ i 1) (cons (car curr) l))))))

;; Produces #t if l1 matches l2 up to the length of whichever is shorter.
;; Allows for a tolerance, where we allow for a certain number of values to not match.
(define mirrored?
  (lambda (l1 l2 tol)
    (cond
     [(or (null? l1) (null? l2)) #t]
     [(eq? (car l1) (car l2)) (mirrored? (cdr l1) (cdr l2) tol)]
     [(> tol 0) (mirrored? (cdr l1) (cdr l2) (- tol 1))]
     [else #f])))

;; Produces #t if pattern is vertically-reflected around the boundary to the right of the column at
;; index x.
(define vertical-reflection?
  (lambda (pattern x)
    (let f ([p pattern])
      (cond
       [(null? p) #t]
       [(let-values ([(left right) (split-at (car p) x)])
          (mirrored? left right 0))
        (f (cdr p))]
       [else #f]))))

;; Searches for a reflection line in pattern, returning its column index if it exists, or #f.
(define get-vertical-reflection
  (lambda (pattern)
    (let ([max-x (length (car pattern))]) ; No possible reflections on the right edge.
      (let f ([x 1]) ; No possible reflections on the left edge.
        (cond
         [(= x max-x) #f]
         [(vertical-reflection? pattern x) x]
         [else (f (+ x 1))])))))

;; Produces a new list of lists from pattern, where each column has become a row.
(define rotate
  (lambda (pattern)
    (let f ([p pattern] [acc (map (lambda (a) '()) (car pattern))])
      (if (null? p)
          acc
          (f (cdr p) (map (lambda (a b) (cons a b)) (car p) acc))))))

;; Produces either the number of columns before the relections line, if the reflection is vertical,
;; or the number of rows multiplied by 100.
(define calculate
  (lambda (pattern)
    (or (get-vertical-reflection pattern)
        (* 100 (- (length pattern) (get-vertical-reflection (rotate pattern)))))))

;; Produces the sum of the calculated values for each pattern in input.
(define solve1
  (lambda (input)
    (apply + 0 (map calculate input))))

;; Produces #t if pattern is vertically-reflected around the boundary to the right of the column at
;; index x.
;; If only one row fails to be mirrored, we check if a single smudge will fix it.
(define vertical-reflection-smudged?
  (lambda (pattern x)
    (let ([failures (let f ([p pattern] [fs '()])
                      (cond
                       [(null? p) fs]
                       [(let-values ([(left right) (split-at (car p) x)])
                          (mirrored? left right 0))
                        (f (cdr p) fs)]
                       [else (f (cdr p) (cons (car p) fs))]))])
      (or (= (length failures) 0)
          (and (= (length failures) 1)
               (let-values ([(left right) (split-at (car failures) x)])
                 (mirrored? left right 1)))))))

;; Searches for a reflection line in pattern that does not match prev-reflection.
(define get-vertical-reflection-smudged
  (lambda (pattern)
    (let ([prev-reflection (get-vertical-reflection pattern)]
          [max-x (length (car pattern))])
      (let f ([x 1])
        (cond
         [(= x max-x) #f]
         [(vertical-reflection-smudged? pattern x)
          (if (and prev-reflection (= x prev-reflection))
              (f (+ x 1))
              x)]
         [else (f (+ x 1))])))))

;; Finds the vertical smudged pattern, falling back to checking the horizontal one.
(define calculate-smudged
  (lambda (pattern)
    (or (get-vertical-reflection-smudged pattern)
        (* 100 (- (length pattern) (get-vertical-reflection-smudged (rotate pattern)))))))

;; Produces the sum of the calculated values for each pattern in input, after correcting "smudges":
;; flipping one r to s or vice-versa.
(define solve2
  (lambda (input)
    (apply + 0 (map calculate-smudged input))))

(printf "~a~n" (solve1 EXAMPLE))
(printf "~a~n" (solve2 EXAMPLE))

(define INPUT
  '(((s r r r s s s s r s r r r s s)
     (s s s r s r r s s s r s r s s)
     (s r s r s r s s s s s s s r r)
     (r r r r r r r s s r s s r s s)
     (r r r r r s r r r s s s r s s)
     (r r s r r s s s s s s r s r r)
     (r r r s r s r r s r s s s r r)
     (r r r r r s r s r r r s s s s)
     (r r r s s r r s r r r r s s s)
     (s s s s r s s s r s s s s r r)
     (s s s r s r r r r r r s r s s)
     (s r s s r s s s r s r r r s s)
     (s r r r s r r r r s s r s s s)
     (s s r r r r r s s s s s s s s)
     (r r r r s s s r s r s s r r r)
     (r r r r s s s r s r s s r r r)
     (s s r r r s r s s s s s s s s))
    ((s s s s r s r s s)
     (s r r r r r r s r)
     (r r s s s s s s s)
     (r r r s s s s s r)
     (s r s r s r s r s)
     (r r s r s r s r s)
     (r r r s s s s s r)
     (r r s s s s s s s)
     (s r r r r r r s r)
     (s s s s r s r s s)
     (s s s s r s r s s))
    ((s s r s s s r r s s s r s s r)
     (r s s s s r r r r s s s s r s)
     (s r r s r r s s r r s r r s s)
     (s s r r s r r r r s r r s s s)
     (r r r s s s s s s s r r r r s)
     (s r r r s r s s r s r r r s r)
     (r s r r r s s s s r r r s r r)
     (s s s s r s s s s r s s s s s)
     (r r r s s s s s s s s r r r r)
     (r s s s s s r r s s s s s r r)
     (r s s s s s r r s s s s s r r))
    ((s r r s s r r s s r r s s s s r r)
     (r s r s r r r r s r s r s s r s r)
     (r s s s s s s s s s s r s s r s s)
     (r s s r r s s r r s s r r r r s s)
     (r s r s s r r s s r s r r r r s r)
     (s s r r s s s s r r s r s s r s r)
     (s r r r r r r r r r r s r r s r r)
     (s s r s r r r r s r s s s s s s r)
     (r s r s s s s s s r s r s s r s r)
     (s r r s s r r s s r r s r r s r r)
     (s r r r r r r r r r r s r r s r r))
    ((s s r r s s r r r r s s r)
     (r r r r r r r s s r r r r)
     (s r r r r s r r r r s r r)
     (r s s s s r r r r r r s s)
     (s r r r r s s r r s s r r)
     (r s r r s r s r r s r s r)
     (s s s r s s s r r s s s r))
    ((s s r r r r s s s s s)
     (r r r r r r r r s r r)
     (s s r s s r s s s r r)
     (s r s r r s r s s r s)
     (r s s s s s s r s s s)
     (s r s r r s r s r s s)
     (s s s s s s s s r r s)
     (s s r s s r s s s s s)
     (s s s s s r s s s s s)
     (r s s s s s s r s s r)
     (r s s s s s s r s s r))
    ((s s r s s r s r r)
     (s s r s s r s r r)
     (r s s s r s s r s)
     (r r s r s s r r s)
     (r s r r s r s r s)
     (r r r s r s s s r)
     (r r s s r r r r r)
     (s s s s s r s s r)
     (s r s s s r s s r)
     (r r s s r r r r r)
     (r r r s r s s s r))
    ((r r r s r r s r s r r)
     (r r r s r r s r r r r)
     (s s s r s s r s r r s)
     (r r s s s r r s s r s)
     (s s r r r s r r s r s)
     (r r s r s r s s r s r)
     (r r r r r r r r r s r)
     (s s s s r s s s s s r)
     (r r s r s r r r s r s)
     (r r s s s r r s r r s)
     (s s s s s s s r s s r)
     (s s r r r r r r r r s)
     (r r s s s r s r s s s))
    ((s s r s r r s r s s r s r r r)
     (r s r r r r r r s r r r s r r)
     (s s s s s s s s s s s r r s s)
     (s s s r s s r r s s s s r r r)
     (r s s s s s s s s r r s s r r)
     (s s r s s s s r s s s r s s s)
     (r r s r r r r s r r s s s r r)
     (s r s r r r r s r s r s s s s)
     (s r r r r r r r r s s s s r r)
     (r r r s s s s r r r s s s r r)
     (s s s s s s s s s s s r s s s)
     (r r r r r r r r r r r s r s s)
     (r r r r r r r r r r s r r s s))
    ((r r s r s r s r r s s)
     (r r s r s r s r r r s)
     (r s s r r r r s r r s)
     (r s s r r r r r s s r)
     (r s s r r r r r s s r)
     (r s s r r r r s r r s)
     (r r s r s r s r r r s)
     (r r s r s r s r r s s)
     (s s r s r s s s s s r)
     (s s r s s s r r s r r)
     (s r r r s s r r s s s)
     (s r s r r r s s r r r)
     (r s r s r s s s r r r)
     (s r r s r s r r s s s)
     (r s r r r r r r s s s)
     (s s s s s s s r r r r)
     (s r r s r s r s r s r))
    ((r r r r s s r r r)
     (r r r r s s r r r)
     (r r s r r r s s s)
     (s r s r r r s r s)
     (s s r s s r s r s)
     (s s r s s r s r r)
     (s r s r r r s r s)
     (r r s r r r s s s)
     (r r r r s s r r r))
    ((r r r r s s s s s s s s r)
     (r r r s s s r r r r s s s)
     (r r r s s r s s s s r s s)
     (s s s s r s s s s s s r s)
     (r r s r r r s r r r r r r)
     (s s r r s s s r r s s s r)
     (r r s s s r r s s r r s s)
     (r r r r r s r r r r s r r)
     (r r r r s r r r r r r s r))
    ((r s s s r s s r r)
     (s s s r s r r r s)
     (s s s r s s r r s)
     (r s s s r s s r r)
     (s r r s s r s s r)
     (s s r s r s s r r)
     (s r r r r r s s r)
     (s s r r s s r s r)
     (s s r r s s r s r))
    ((s r s s s s r)
     (r s r r r r r)
     (r s r s s s r)
     (s r r s s s s)
     (s s s s r s s)
     (r r s s r r s)
     (s s s r s r s)
     (s s s r s r s)
     (r r s s r r s)
     (s s s s r s s)
     (s r r s s s s)
     (r s r s s s r)
     (r s r r r r r)
     (s r s s s s s)
     (s r s s s s s))
    ((r r s r s r s r s s s r r r s)
     (r r r s r s s s r s s r r s r)
     (r s r r s s s r r s s s r s r)
     (s s r s r r s r s s s s r s s)
     (r r r r s r r r r s s r r s r)
     (r r r r s s r s s s s r r s r)
     (s s r r s r s s s s s r s r s)
     (s s s s r s s r r s r s s s s)
     (r r r s r r r r s s s r r s r)
     (s s s s s r s r r s r s s s r)
     (s s r r s r r r r r r r s s s)
     (s s r r r s s s s r r r s s r)
     (s s r r r s s s s r r r s s r))
    ((r r r r s r s r r s s)
     (r r r r s r r r r r r)
     (r r r r s r r r r r r)
     (r r r r s s s r r s s)
     (r r r r r r r s r r r)
     (s r r s s s r s s s r)
     (s r r s r r s s r s s)
     (r r r r s r r s s r s)
     (r s s r s s s s r r r)
     (r r r r r s s s s r s)
     (r s s r r s s r s s r)
     (s s s s r r s s s s r)
     (r r r r s r s s r s r))
    ((s s s r s s s r s s r s s)
     (r s s r s s r r r r r r s)
     (r s s r s s r r r r r r s)
     (s s s r s s s r s s r s s)
     (s s r r s r s s s s s s r)
     (s r s r r r s r s s r s r)
     (s r r s r s s r s s r s s)
     (s s s r r r r s s s s r r)
     (s s r s r r s s s s s s r)
     (s r s r r s r s r r s r s)
     (r r s r r s s r s s r s s)
     (s r r r s r s s s s r s r)
     (s r r s s s s r s s r s s)
     (s s r s s r r s s s s r r)
     (r s r r r s s s r r s s s)
     (s s r s s r s r r r r s r)
     (r s r r r r s s s s s s r))
    ((r r s s r s s s s r r)
     (r r s s r r s s s r r)
     (s s s r s s s r r r s)
     (s s s s s r r s s s r)
     (r r r r r s r s s r s)
     (r r s s s s s s s s s)
     (r r s s r r s r s s r))
    ((s s s s r s s s s s s s s s s)
     (r r s r s s s s r r s s r r s)
     (r r s r s r s r s s r r s s r)
     (r r r r s r r r s s s s s s r)
     (s s r r s r r s s r s s r s s)
     (r r s s s r r s r r r r r r s)
     (s s r s r r s r r r r r r r s))
    ((r s r r r r s r r r s s s s s)
     (r r s s s s r s s r s r s s s)
     (s s s s s s s r s s r r s r r)
     (s s s s s r s r s s r r s r r)
     (r r s s s s r s s r s r s s s)
     (r s r r r r s r r r s s s s s)
     (r r s s s r r s r r r s r r r)
     (r r r r r r r r s r s r s r r)
     (s s s s r s r r r r r r s r r)
     (s s r r s r s s r s r r r r r)
     (s s s r r r r s r s r r r r r))
    ((r r s r r r r)
     (s r s s r s s)
     (r r r r r s r)
     (r s r r r s r)
     (r r r s s s r)
     (r r r s s s r)
     (r s r r r s r)
     (s r r r r s r)
     (s r s s r s s)
     (r r s r r r r)
     (r r s r r r r)
     (s r s s r s s)
     (s r r r r s r)
     (r s r r r s r)
     (r r r s s s r))
    ((s r r s s s r)
     (r s s r r r s)
     (r r r r s s s)
     (r r r r s s s)
     (r s s r r r s)
     (s r r s s s r)
     (r r s r s r s)
     (r r r r r r s)
     (r s s r s s s)
     (r r r r s s s)
     (s r r s s r s)
     (r r r r r s s)
     (s r r s s s r))
    ((s s s s r r r s s s r r s s s)
     (s s r s s s s r s s r r s s r)
     (s s s r s s r s s s s s s s s)
     (r s s s s s s s s r s s r s s)
     (r r s r r r r s r r r r r r s)
     (r r r r r r r r r r s s r r r)
     (r s s r s s r s s r s s r s s)
     (r r s s s s s s r r r r r r s)
     (r s r r s s r r s r s s r s r)
     (s s r s r r s r s s s s s s r)
     (r r s r r r r s r r s s r r s)
     (s s r s r r s r s s r r s s r)
     (s s r r s s r r s s s s s s r))
    ((r r s s s r s)
     (s s s s r r s)
     (r r r r s s r)
     (s s s r s s r)
     (s s s r s s r)
     (r r s s r r s)
     (r r r s r r s)
     (r r s r s s r)
     (s s r s r r s)
     (r r r s r r s)
     (s s s r s s r))
    ((s s s r r r r s s)
     (s r s r s s r s r)
     (s r r r s s r r r)
     (s s r s s s s r s)
     (r r s s r r s s r)
     (r r s r s s r s r)
     (r s s r r r r s s)
     (s r r s s s s r r)
     (r s r s r r s r s)
     (s r s s s s s s r)
     (r r r s s s s r r)
     (s r r s s s s r r)
     (s r s s s s s s r)
     (r s r s r r s r s)
     (s r r s s s s r r)
     (r s s r r r r s s)
     (r r s r s s r s r))
    ((s r r s s r s r r r r r r s r s s)
     (r s s r s r r r s r r s r r r s r)
     (s s s s s s r r s s s s r r s s s)
     (r r r r s r r r r s s r r r r s r)
     (s s s s r r s r r r r r r s r r s)
     (s s s s r r s r s s s s r s r r s)
     (r s s r r s r r r s s r r r s r r)
     (s r r s r s s s s r r s s s s r s)
     (r s s r r s s r s r r s r s s r r)
     (r r r r s r s r s s s s r s r s r)
     (s r r s r r s r s r r s r s r r s)
     (s s s s s s s r r r r r r s s s s)
     (s r r s s s r r r r r r r r s s s)
     (s r r s s s s s s s s s s r s s s)
     (s r r s s s r r r r r r r r s s s))
    ((r r r r r r r r s s r s r r s r s)
     (s r r s r r r s s r s r r r r r r)
     (r s s s r r r s s r r r s r r s r)
     (r s r s r r s s s s r s s r r s s)
     (r s s r s s s s r r s r s r r s r)
     (r r s r r r r r r s s s r s s r s)
     (s s s r s s r s s s s r s r r s r)
     (r r s r s s s s r r s s s r r s s)
     (r r s r s s s s r r s s s r r s s))
    ((r s r r r s s r r r r)
     (r r s s r r s r s s s)
     (s s s r s s s r s r r)
     (s r r s r r r r r r r)
     (r s s r s s r s s r r)
     (r s r r r r s s s s s)
     (r s s s r s s r r s s)
     (s s s s r s s r s r r)
     (s r s r r r s s s s s)
     (r r s s r r r r r r r)
     (r s s r s r r s s s s)
     (s s s r s s s r r s s)
     (s s s r s s s r r s s)
     (r s r r s r r s s s s)
     (r r s s r r r r r r r))
    ((r r s s r s s s s s s s s)
     (s r r r s r r s s s r r s)
     (s s s s r r r s s r r r r)
     (r r r s r r r s r s r r s)
     (s s s r s r s s s s r r s)
     (s s s s r r s r r r s s r)
     (r r s r r r r s s r r r r)
     (s r r s s r r r s s s s s)
     (r s r r r r r r r r s s r)
     (r s r s r s r s r s r r s)
     (s s r s s s r s s s s s s)
     (s s r s s s r s s s s s s)
     (r s r s r s r s r s r r s)
     (r s r r r r s r r r s s r)
     (s r r s s r r r s s s s s))
    ((s s r r r s r r s)
     (s s r s s s r r s)
     (r s r s s s r r s)
     (s s r r r s r r s)
     (r s s s s s r r s)
     (s r r r r s r r s)
     (s r s r s r r r r)
     (r s r s r s s s s)
     (s s s r r r r r r)
     (r s s s r s r r s)
     (r s r r r s r r s)
     (r s s r s s s s s)
     (r r r s s s s s s)
     (s r s r r s s s s)
     (s r r r s r s s r)
     (r s s r r r r r r)
     (s r s r r r r r r))
    (
     (s s s s s s s s s s r)
     (r r s r r r r s r r r)
     (s r s s r r s s r s s)
     (s r r s s s s r r s r)
     (r r r r s s r r r r s)
     (r r s s r r s s r r r)
     (s s r s s s s r s s r)
     (r s r r r r r r s r r)
     (r s r r r r r r s r s)
     (s s r s s s s r s s r)
     (r r s s r r s s r r r))
    (
     (s r r r s r s s r s r)
     (s s s r s s s s s s r)
     (r r r s r r r r r r s)
     (r r s s s r s r r s s)
     (r r r r r s r r s r r)
     (r s r r r r s s r r r)
     (r r s s r s s s s r s)
     (r r s s r s s s s r s)
     (r s r r r r s s r r r))
    (
     (s s s s s s s s s r s s s s r s r)
     (r s r s s r s r r s s s s s s r s)
     (r s s s s s s r r s r r r r s s s)
     (r s s r r s s r r r r s s s s s s)
     (s r s s s s r s r s s s s s s s s)
     (r s s s s s s r s s s s r r r r s)
     (s s r r r r s s s s r s r s r s r)
     (r s r r s r s r r s r r r r r s s)
     (s r s s s s r s s r r r r r r r r)
     (s r s r r s r s r s r r r s r s r)
     (s r r s s r r s s s r r r r s s r)
     (s s r r r r s s s r s r s r s s r)
     (s r s r r s r s s r s r r r s r s)
     (s s s r r s s s s s r s s r s r s)
     (s s s r r s s s s s r s s r s r s))
    (
     (s r r s s s r r r s r r s r s)
     (r s s r r r s r r r s s r r r)
     (s s s s r s s s r s s r s r r)
     (s s s s r r r r s s r s s r r)
     (s s s s r r r r s r r s s r r)
     (s s s s r s s s r s s r s r r)
     (r s s r r r s r r r s s r r r)
     (s r r s s s r r r s r r s r s)
     (s r r s r s s s r s r s s r r)
     (s s s s r r s s r r s r r s r)
     (s s s s s r s s s r r s r r r)
     (s s s s s r s s s s r r s r r)
     (r r r r r s s s r s s s s s r)
     (s s s s s s s r s r s s r s s)
     (r r r r s r s s r s r s s r r))
    (
     (r r r r s s s r r s r s r)
     (r r s r s s s s r r s s r)
     (r r s r s s s s r r s s r)
     (r r r r s s s r r s r s r)
     (r s s r s r s s r s r r s)
     (s s s s s s r r s s s r r)
     (r r r s r s r s r s r r s)
     (s s s r s s s r r r s r s)
     (r s r s s r s s r r r r s)
     (r r r s s r s s r r r r s)
     (s s s r s s s r r r s r s))
    (
     (s s r r s r r s r s r r r)
     (s r s s r s s s r r r r s)
     (r s r s s r r s s r s s s)
     (s s r r s s r r s s r r r)
     (s s r s r r s r r r s s r)
     (s r r r r r r r r r s s r)
     (s r r r r r r r r r s s r)
     (s s r s r r s r r r s s r)
     (s s r r s s r r s s s r r)
     (r s r s s r r s s r s s s)
     (s r s s r s s s r r r r s)
     (s s r r s r r s r s r r r)
     (s s r r s r r s r s r r r)
     (s r s s r s s s r r r r s)
     (r s r s s r r s s r s s s)
     (s s r r s s r r s s s r r)
     (s s r s r r s r r r s s r))
    (
     (s r r s s s r r r r s s s r s)
     (s r r s s s r r r r s s s r s)
     (s r r s s s s r r s r r r r r)
     (r s r r r r s s s r r s r s s)
     (s r s r s s s r s s s r s s r)
     (s r r s r s r s s r s s s r r)
     (r s r r s s s r s s s s r r s)
     (s s r s r r r r r s r r r r r)
     (r r s r r r r r r s s r r r s)
     (s r r s r r s s s r r s r r r)
     (r s r s s s r s r s s s s r s)
     (s r s s r r r r r r r r r r r)
     (s r s s s s r r r s r r r r s)
     (s r s s s s r r r s r r r r s)
     (s r s s r r r r r r r r r r r)
     (r s r s s s r s r s s s s r s)
     (s r r s s r s s s r r s r r r))
    ((r r r r r r s r s)
     (r r r r r r s r s)
     (s r r r r s s s s)
     (r s r s s r s s s)
     (r s r r s r r s r)
     (s r s s r s r s s)
     (r s r r s r s r r))
    ((s s s r s s s s s)
     (r s s r r r s s s)
     (r r r s r r r r r)
     (r r r r r r r s s)
     (r r r r r r r s s)
     (r r r s r r r r r)
     (r s s r r r s s s)
     (s s s r s s s s s)
     (r s s s r s r r s)
     (s s r r s r r r s)
     (s s r r s s r r s)
     (r s s s r s r r s)
     (s s s r s s s s s)
     (r s s r r r s s s)
     (r r r s r r r r r))
    ((s r r r s s s r s r s s r r s)
     (s r s r s s s s r s r r r r r)
     (s s s s s s r s s s s r r s s)
     (s s s r r r s r r r r s s s s)
     (s s r s s s s s r s s s s r r)
     (r s s r s r s r s s s r r r s)
     (r s s r s s s r s s s r r r s)
     (r s r r s s r r s r s s r r s)
     (r s r r s s r r s r s s r r s)
     (r s s r s s s r s s s r r r s)
     (r s s r s r s r s s s r r r s))
    ((r r s s r r r r s)
     (r s s s s r s r r)
     (s s r r s s r s r)
     (r s s s s s s s r)
     (r s r r s r r r s)
     (r s s s s r r s s)
     (r s r r s r r r s)
     (r s r r s r r r s)
     (r s r r s r r r s)
     (r s r r s r r r s)
     (r s s s s r r s s))
    ((r r r r s s s s r r r r r)
     (s r r s r r r r s r r s s)
     (s r s r s s s s r s r s s)
     (r s r s r s s r s r s r r)
     (s r s r s s s s r s r s s)
     (s r s r s r r s r s r s s)
     (r r s r s s s s r s r r r)
     (r s r s r s s r s r s r r)
     (s s r s s s s s s r s s s)
     (r r s s r r r r s s r r r)
     (r r r r s r r s r r r r r)
     (s r r r r r r r r r r s s)
     (s r r r r s s r r r r s s)
     (s r r s s r r s s r r s s)
     (r r s s r r r r s s r r r)
     (r r r s s s s r s r r r r)
     (r r r r s s s s r r r r r))
    ((s r r r r s s r r s s r r r r s r)
     (s r r r r s s r r s s r r r r s r)
     (r r r s s r r s s r r s s r r r r)
     (s s r r s r r s s r r s r r s s r)
     (s s r r r s r r r r s r r r s s r)
     (s s s r s s r r r r s s r s s s s)
     (r s r s s s r r r r s s s r s r s)
     (r s r s s r r r r r r s s r s r r)
     (r r s r s s s s s s s s r s r r r)
     (r s r s r s s r r s s r s r s r r)
     (s s r s r r r s s r r r s r r s r)
     (s r r r r r r r r r r r r r r s s)
     (s r r r s s s s s s s s r r r s r)
     (r r r r r r s r r s r r r r r r r)
     (r r r s s s s s s s s s s r r r r))
    ((s r s s r s s s s r s s s s s)
     (r r s s r s s s s r s s r r s)
     (r s r s r s s s s r s r s r r)
     (r r s r r r s s r r r s r r r)
     (r r r s s r s s r s s r r r s)
     (r s r s r r r r r r s r s r r)
     (r s r s r r r r r r s r s r r))
    ((r r r r s s r)
     (s r r s r r s)
     (s s s s r s s)
     (r r r r s s s)
     (r r r r s s r)
     (r r r r r s r)
     (s s s s s r r)
     (s s s s s r r)
     (r r r r s r r))
    ((r r s s s s r r r r r)
     (s r r s r r r s r r r)
     (r s r s s r s r r s s)
     (r s r r r r s r s r r)
     (s s r s s r s s s r s)
     (r s r r r r s r r s r)
     (s r r s s r r s s s r)
     (s r s r r s r s s r s)
     (s r r r r r r s s r s)
     (s r s r r s r s s s s)
     (r r s r r s r r r s r)
     (s s s r r s s s r s s)
     (s s s r r s s s r s s))
    ((s r s s r s s s r s r s r)
     (s r s s r s s s r s r s r)
     (s s s r r r r r s s s r r)
     (s r r r r r r s s s r r s)
     (r s r s r r s r s r r r r)
     (s r r s r r s s r r r r r)
     (s r r s r r s s r r r r r)
     (r s r s s r s r s r r r r)
     (s r r r r r r s s s r r s)
     (s s s r r r r r s s s r r)
     (s r s s r s s s r s r s r))
    ((s r s r r r r s r s s r r s s r r)
     (r s r r r r r r s r s r s s r r r)
     (s s r s r r s r s s r s s s s r s)
     (r r r s r r s r r r r r s s r s s)
     (s r r r s s r r r s s s r s r s s)
     (r s s r r r r s s r s s r r s r s)
     (s r s s s s s s r s r r s s s r s)
     (r s s r s s r s s r s s s s r r s)
     (s s s s r r s s s s r r s s r r s)
     (r r r s s s s r r r s r r s r r s)
     (r r r s s s s r r r s r r s r r s)
     (s s s s r r s s s s r r s s r r s)
     (r s s r s s r s s r s s s s r r r)
     (s r s s s s s s r s r r s s s r s)
     (r s s r r r r s s r s s r r s r s))
    ((s s s s s s s r s)
     (s s r s s s r r r)
     (r r s s s s r r s)
     (s s r s r s s r s)
     (r r r r r r r s r)
     (s s s r r s s s s)
     (r r r s r s r s s)
     (s r r r s s s s r)
     (r r r s s s s s s)
     (r r s r r r r r r)
     (r r s r s r s r s)
     (r r s s s r r s s)
     (s s s r s s r s r)
     (r r r s s s s r r)
     (r r r r s r r s r)
     (s s r s s r s r s)
     (s s r s s r s r s))
    ((r r s s r s r r s s s s s s r r r)
     (r r s r r s r r s r r s r s r s s)
     (s s r r r r s s r r r s r r r s s)
     (r s s s s s s r r s r r r s s s s)
     (s s s r r s s s s s s s s s s s s)
     (r s r r r r s r s s r s s r r r r)
     (s r s r r s r s r r r r r r s s s)
     (r r s s s s r r s r s r s s s s s)
     (r s r r r r s r r s s s s r s s s))
    ((r s r r r r r r s r s s s s s r r)
     (r r s r s s r s r r r r r s s s r)
     (s r s s s s s s r s s r s s s s s)
     (s s r r r r r r s s s r r s r s r)
     (r r s s r r s s r r s s r r r s s)
     (s s r s s r s r s s s s r r s r r)
     (r s r s s s s r s r r s s s r r r)
     (s r r r s s r r r s r r s s r r r)
     (r s r r r r r r s r s r r r s r r)
     (s r s r s s r s r s s s r s s r s)
     (s s s s r r s s s s s r r s r s r)
     (s s s s r r s s s s s r r s r s r)
     (s r s r s s r s r s s s r s s r s)
     (r s r r r r r r s r s r r r s r r)
     (s r r r s s r r r s r r s s r r r))
    ((r s r r r r s r r s r r r r s r s)
     (s r s s s s s r r s s s s s r s r)
     (s r s s s s s r r s s s s s r s r)
     (r s r r r r s r r s r r r r s r r)
     (r r s r r s s r r s s r r s r r r)
     (r r s r s s s r r s s s r s r r s)
     (s s r s r r s s s s r r s r s s s)
     (r r r r s s r r r r s s r r r r s)
     (r r r r s r s r r s r s r r r r r)
     (r r s s s s s r r s s s s s r r r)
     (s s s s r r r s s r r r s s s s r)
     (r s s r s r r s s r r s r s s r s)
     (r r r s r r r r r r r r s r r r s))
    ((s s r r s r r)
     (r s s r r s s)
     (s s r r r s r)
     (r r s s s s r)
     (r s s r s r s)
     (r s s r s r s)
     (r r s s s s r)
     (s s r r r s s)
     (r s s r r s s)
     (s s r r s r r)
     (s s r r s r r))
    ((r s s s s r r r r r r s s s s)
     (r r s r r s s r r s s r r s r)
     (r r s r r s r r r r s r r s r)
     (s r r r s r s r r s r s r r r)
     (s r r r s r s r r s r s r r r)
     (r r s r r s r r r r s r r s r)
     (r r s r r s s r r s s r r s r)
     (r s s s s r r r r r r s s s s)
     (r s r r s s s s s s s s r r s)
     (r s s r r s s s s s s r r s s)
     (s r s r r s s r r s s r r s r)
     (r s r s s r s s s s r s s r s)
     (s s s s r s s r r s s r s s s)
     (s r s s s r s s s s r s s r r)
     (r r s s r r r s s r r r s s r)
     (s s r s r r r s s r r r s r s)
     (s r r r r r s r r s r r r r r))
    ((s r s s r s r s s s s r s)
     (s r s s r s r s s s s r s)
     (s s s s s r r r r r s r r)
     (r s s r r r r s s s s r r)
     (r r s s r r r r r r r r r)
     (r s r r r s s r r r r s s)
     (s r s s s s s s r r s s s))
    ((r s r s s r s s r s s r s)
     (r s s r r s s s s r r s s)
     (s s s r r s s s s r r s s)
     (s r r s s r r r r s s r r)
     (r s r r r r s s r r r r s)
     (r s r s s r s s r s s r s)
     (r s r r r r s s r r r r s)
     (s s s r r s s s s r r s s)
     (r r s s s s r r s s s s r)
     (s r r r r r r r r r r r r)
     (s s r r r r s s r r r r s)
     (r s s r r s s s s r r s s)
     (s r s r r r r r r r r s r)
     (s r r s s r r r r s s r r)
     (s s r s s r s s r s s r s))
    ((r r r r r r s r s)
     (s r s s r s r r s)
     (s r r r r s r s s)
     (s r r r r s r s s)
     (s r s s r s r r s)
     (r r r r r r s r r)
     (r r r r r r s s r)
     (r s r r s r s r r)
     (s r r r r s s r s)
     (r r s s r r s r s)
     (s r s s r s s r s)
     (r r s s r r s r s)
     (s r s s r s r r s)
     (s s s s s s r r s)
     (r r s s r r r r r))
    ((s s s s s r r s r r s)
     (s s s s r s s r r r r)
     (r r r r r s r s r r s)
     (s r r s r s s r r s s)
     (s s s s s r s s r r r)
     (r r r r s s s s r s s)
     (r r r r s r r s r s s)
     (s s s s r s r s s s s)
     (s s s s r s s r s r s))
    ((s r r r s r s s r r r r s r s s r)
     (s r s r s r r r r r r r s r s s r)
     (s s r s r r r s r r r s s r r r r)
     (s s r r s r s s r r s r r s r r s)
     (s r r s s s s r r r s r r s s s s)
     (s r r r r s s r r s r r r r r r r)
     (r r s r r r r r r s r r r s r r s)
     (r r s s s r r s s r s s s s s s s)
     (r s r r r r r r r s r s r s r r s)
     (r s r r r r r r r s r s r s r r s)
     (r r s s s r r s s r s s s s s s s)
     (r r s r r r r r r s r r r s r r s)
     (s r r r r s s r r s r r r r r r r)
     (s r r s s s s r r r s r r s s s s)
     (s s r r s s s s r r s r r s r r s)
     (s s r s r r r s r r r s s r r r r)
     (s r s r s r r r r r r r s r s s r))
    ((s s s r r s s s s)
     (r s s r r s s r r)
     (s s r r r r s s s)
     (r r s s s s r r r)
     (s r r s s r r s s)
     (r s r s s r s r r)
     (s r s r r s r s s)
     (r s r r r r s r r)
     (s s r s s r s s s)
     (r s r r r r s r r)
     (r s r s s r s r r)
     (s s r r r r s s s)
     (r r s r r s r r r)
     (s r s r r s r s s)
     (s r r r r r r r r)
     (s s s r r s s s s)
     (s r s r r s r s s))
    ((s r r s s r s)
     (s s s r s s r)
     (s s s s r s s)
     (s s s r s s r)
     (r r s r r s r)
     (s s s s r s r)
     (s s s s r s r))
    ((r r s r s r r r r s r r s s r)
     (r r r r r r r r s s s r r r r)
     (s s s s s s r s r r s s s s s)
     (s r r r r r s r r r s s r r s)
     (s s r r r s s r s s s r s s r)
     (s s s s r r s r r s r r r r r)
     (r r r s s s r s s r r s s s s)
     (s r s s r r r r r r r r s s r)
     (s s s s r s r s s r r s s s s)
     (s s r r s s r r s s s s s s s)
     (s s r r s s r r s s s s s s s)
     (s s s s r s r s s r r s s s s)
     (s r s s r r r r r r r r s s r)
     (r r r s s s r s s s r s s s s)
     (s s s s r r s r r s r r r r r))
    ((s r r s r r r r s s r s r)
     (s s s r r r s s s r r r s)
     (s s s r r r s s s r r r s)
     (s r r s r r r r s s r s r)
     (r s r s s r r s s r r r r)
     (s s s r s s r s s s s r r)
     (s r s r r s s s r r s r r)
     (r s r s s r r s r r r s s)
     (s r r r r s s r s r s s s)
     (r s r r s r s s s r s s r)
     (s s s s r r r s s r r s s)
     (r r r s r s s r r s s r s)
     (r s r s r s s r r s s r s)
     (s s s s r r r s s r r s s)
     (r s r r s r s s s r s s r)
     (s r r r r s s r s r s s s)
     (r s r s s r r s r r r s s))
    ((s r s s r s s)
     (r s s s s r r)
     (s s r r s s s)
     (r r s r r r r)
     (r s r r s r r)
     (s r s s r s s)
     (r s s s s r r))
    ((r s r r r s s s s)
     (r s r r r s s s s)
     (r s r s r r r s s)
     (r r s r s s r r r)
     (s s r r s r s s r)
     (s r r r s r r r r)
     (r s s r r r r r s)
     (r s s r r r r r s)
     (s r r r s r r r r)
     (s s r r s r s s r)
     (r r s s s s r r r)
     (r s r s r r r s s)
     (r s r r r s s s s))
    ((s r s s r s r s r)
     (r s r r s r s s s)
     (r r r r r r s r s)
     (s s r r s s r r r)
     (r r s s r r r r s)
     (r s r r s r s s s)
     (s r r r r s r s r)
     (s r r r r s r s r)
     (r s r r s r s s s)
     (r r s s r r r r s)
     (s s r r s s s r r))
    ((r s r s s r r r s s s)
     (r s r s s r r r s s s)
     (r r r s s r s r r s r)
     (s s s r r s s s s r r)
     (s s s s s s s s r s r)
     (s r s r r s s r r r r)
     (r r r r r r r r s s s)
     (s s r r r s r r s s s)
     (r s r r r r s r r s s)
     (r s r s r s s r s s s)
     (s r s s s s s s r s r)
     (r r r s s r s r r s s)
     (r r s r r r s r s r r)
     (s r s r r r s r s r r)
     (r r r s s r s r r s s))
    ((s s s s r s r r s s s)
     (s s r r r s r s s r r)
     (s s r r r s r s s r r)
     (s r s s r s r r s s s)
     (r s s s r s s s r r r)
     (s r r s s r r r s s s)
     (s s r s r r s r s s s))
    ((s r s s s s r s s s s s s)
     (r s r r r r s r r r s s r)
     (r s s s s s s r r r r r r)
     (r s s r r s s r s r r r r)
     (r r s r r s r r s r r r r)
     (s s r r r r s s r s s s s)
     (r s s s s s s r r r r r r)
     (s r s s s s r s s s r r s)
     (s r s s s s r s s s s s s)
     (r r s r r s r r r r s s r)
     (s s s s s s r s s s s s s)
     (s r r r r r r s s s s s s)
     (s r r r r r r s r s r r s)
     (r r r s s r r r r r s s r)
     (r s r s s r s r s s s s s)
     (r r s s s s r r r r s s r)
     (r s s r r s s r s s s s s))
    ((s s s r s s s s s s r r r r r)
     (r s r r r r r s s r r s s r s)
     (r r r r s r s r s s r r s r s)
     (s s r r s s r r r r s r r s r)
     (r s s r s r s s r s s r r r r)
     (r s r s r s r r r s r r s r r)
     (r s r s r s r r r s r r s r r)
     (r s s r s r s s r s s r r r r)
     (s s r r s s r r r r s r r s r)
     (r r r r s r s r s s r r s r s)
     (r s r r r r r s s r r s s r s)
     (s s s r s s s s s s r r r r r)
     (s s s r s s s s s r r r r r r))
    ((r s r s r r r s s r r r s r s r r)
     (r s s s r s s s s s s r s s s r r)
     (r s s s r s s s s s s r s s s r r)
     (r s r s r r r s s r r r s r s r r)
     (s r r r s r s s s s r s r r r s r)
     (s s s r s r r r r r r s r s s s s)
     (r s s r s s s s s s s s r s s r r)
     (s s s r s s s r r s s s r s s s s)
     (r s r s s s r r r r s r s r s r s))
    ((r r s r r r r r r s r r r r s r r)
     (r s r s r s s r s r s r r s r s r)
     (r r s r r s s r r s r r r r s r r)
     (s s r s s s s s s r s s s s r s s)
     (r s s r r r r r r s s r r s s r r)
     (r r r s r r r r s r r r r r r s r)
     (s s s s r s s r s s s s s s s s r)
     (r r r s s r r s s r r r r r s s s)
     (r s r r s s s s r r s r r s r r s)
     (r r s r r s s r r s r r r r s r r)
     (s r s s s s s s s s r s s r s s s)
     (r r s s s s s s s s r r r r s s s)
     (r r s s r s s r s s r r r r s s r))
    ((r r s r s s s)
     (r r s s s s s)
     (r s s s s s r)
     (s r r r r s r)
     (s r r s r r r)
     (s s r s s s r)
     (r s r r r s r)
     (s r r s s r r)
     (s r r s s r r)
     (r s r r r s r)
     (s s r s s s r)
     (s r r s r r r)
     (s r r r r s r))
    ((r r s s s r s r s r r)
     (s r s s s s r s s s s)
     (r s r r r r s s r r s)
     (r s s s r r r s r r r)
     (r r s s r r r s r r r)
     (r s r r r r s s r r s)
     (s r s s s s r s s s s)
     (r r s s s r s r s r r)
     (r r s s s r s r s r r))
    ((r s s s s r s s s s r r s s s)
     (s s r r r s s s s r r r r s s)
     (s s r r r r s s s r r r r s s)
     (r s s s s r s s s s r r s s s)
     (r r s s r s r r s r s s r s r)
     (s s r s s s r r r r r r r r r)
     (s s s r r r r r s s s s s s r)
     (s r s r r r s r r r r r r r r)
     (s s r s s s r s s r r r r s s)
     (r s s s r s s r s s r r s s r)
     (s r r r r r s r r s s s s r r)
     (r r s s s r s r s s s s s s r)
     (s s s s r r r s r s r r s r s))
    ((s r s s r s s r s s r)
     (s r s s r s s r s s r)
     (r s r r r r r r r r s)
     (s s s r r s s r r s s)
     (r r r r s s s s r r r)
     (s r s r r s s r r s r)
     (s r s s r r r r s s r)
     (r r r r r s s r r r r)
     (r r r s r s s r s r r)
     (r r s r s r r s r s r)
     (r r r r s s s r r r r)
     (r s r s r r r r s r s)
     (r r r r s r r s r r r))
    ((r r r s s r r r s s s s r)
     (s r s r r s r s r s s r s)
     (r s r r r r s r r r r r r)
     (s r r r r r r s s r r s s)
     (r r r r s r r r s s s s r)
     (s r s s s s r s r r r r s)
     (r s r s s r s r r r r r r)
     (r r s r r s r r r r r r r)
     (s r s s s s r s s r r s s)
     (s s r s s r s s s s s s s)
     (r s r s s r s r r s s r r)
     (s r r r r r r s s s s s s)
     (s s r r r r s s r r r r s))
    ((s r r s r r s s r r s r r)
     (r r r s s r s s r s s r r)
     (r r r s s r s s r s s r r)
     (s r r s r r s s r r s r r)
     (s s r r r s r r s r r r s)
     (r r s r s r r r r s r s r)
     (s s s s r s r r s r s s s)
     (s r s r s s r r s s r s r)
     (s r s s r r s s r r s s r)
     (s s r s r r r r r s s r s)
     (r r r s r s r r s r s r r)
     (s s r s s s r r s s s r s)
     (r s s r s r r r r s r s s))
    ((r s s r s s s s r r r r r r r r r)
     (r s s s s s r r r r r r s s r r r)
     (r r r s r s s s r r r s s s s r r)
     (r r r s r s s s r r r s s s s r r)
     (r s s s s s r r r r r r s s r r r)
     (r s s r s s s s r r r r r r r r r)
     (s s s r s s r s s r s s r r s s r)
     (r s s r s r s s s s r r r r r r r)
     (s s r s r s r s r s s r r r r s s)
     (r s s r s s r r s r s s r r s s r)
     (s s s r r s s r r s r r r r r r s)
     (r s s r s r s s s r r r r r r r r)
     (s r s r r r s s s s s s r r s s s))
    ((r r s r s s s)
     (s s r s s s s)
     (s s r s s s s)
     (r r s s s s s)
     (s s s r s s r)
     (s s s r s s r)
     (s s r s r r s)
     (r r s r r r r)
     (s s s r r r r)
     (s s r s r s r)
     (r r r s s r r)
     (r r r s s r r)
     (s s s s s s r))
    ((s s s s s s r r s)
     (r s s r r s s s s)
     (s r s s s r s r r)
     (s r r r s s r r r)
     (s r r r r s s s s)
     (s r r r r s s s s)
     (s r r r s s r r r)
     (s r r s s r s r r)
     (r s s r r s s s s)
     (s s s s s s r r s)
     (s s s s s s r r s))
    ((s r r s r r s r s r s r s r r r r)
     (r s s r s s s r r r s r r s s s s)
     (r s s r s s s r r r s r r s s s s)
     (s r r s r r s r s r s r s r r r r)
     (s r r s r s s s s s s s s r s s s)
     (r s s r r r r r r s s r r r s s s)
     (s r s s r r r s r s s r r s s s s)
     (s r r s r r r r s r r r s s r r r)
     (r s s s r s r r s s r r s s s s s)
     (r s r s s s s r s s r r s r r r r)
     (s s r r s s r s s r r r r r s r r)
     (r s r s s s r s s s r s s s s r r)
     (s s r s r s r s r s r s s s s s s)
     (s s r s s s s s r r r r r r s r s)
     (r s r r r r r s r r s s s r r r r))
    ((r r s r s s r s r r r s r r s)
     (r r s s r r s s r r s s s r s)
     (s r r r r r r r r s s s r s s)
     (s r s r s s r s r s r r s s r)
     (r r r r s s r r r r s s s r r)
     (r r s s r r s s r r r s r r s)
     (s r s s s s s s r s r s r r s)
     (s s r s s s s r s s s s s r r)
     (r s r s r r s r s r r r s s s)
     (s r r s r r s r r s s s s s r)
     (s r r s r r s r r s s r s s r)
     (r s r s r r s r s r r r s s s)
     (s s r s s s s r s s s s s r r)
     (s r s s s s s s r s r s r r s)
     (r r s s r r s s r r r s r r s)
     (r r r r s s r r r r s s s r r)
     (s r s r s s r s r s r r s s r))
    ((s s s s r r r)
     (s s r r r s r)
     (s s s r s r s)
     (r r r s r s r)
     (s s s s r s r)
     (s s s s r s r)
     (r r r s s s r))
    ((s s s s r r s s s)
     (s s s r s s r s s)
     (r r s r s s r s r)
     (r r r s s s s r r)
     (s s r r s s r r s)
     (r r r s s s s r r)
     (r r r r s s r r r)
     (s s r r s s r r s)
     (r r r r s s r s r)
     (s s r r r r r r s)
     (s s r s r r s r s))
    ((r r s s r r r r r r s s r r r)
     (s s r r s s s s s r r r r s s)
     (s s r r s s s s r r r r r r s)
     (s r s s r s r s s s r r s s s)
     (r r s s r r r r s s s s s s r)
     (s s s s s s r s r r s r r r s)
     (r s s s s r s r s s s s s s r)
     (s s s s s s s r s s s s s s r)
     (r r r r r r s r r s r r s r r)
     (r s s s s r s s s r r r r s s)
     (r r s s r r s s r s r r s r s)
     (r r s s r r s r s r r r r s r)
     (s s s s s s r r r r s s r r r))
    ((s r s s r s r r s s r)
     (s r r s r r r r r r s)
     (r s s s r s r r s s s)
     (r r s s r s s r s r s)
     (r s r r s s s r r s r)
     (r s r r r s s s s r s)
     (s s s s s r s s s s r)
     (s s s s s r s s s s r)
     (r s r r r s s s s r s)
     (r s r r s s s r r s r)
     (r r s s r s s r s r s)
     (r s s s r s r r s s s)
     (s r r s r r r r r r s)
     (s r s s r s r r s s s)
     (s r s s r s r r s s s)
     (s r r s r r r r r r s)
     (r s s s r s r r s s s))
    ((r s r r r s s s s r r r s)
     (r s r r r s s s s r r r s)
     (s r s s s s r r s s s s r)
     (s r s r r r r r r r r s r)
     (s s r r s s s s s s r r s)
     (s r s r s r s s r s r s r)
     (r s r r r r s s r r r r s)
     (r r r r s r r r r s r r r)
     (s r s r r s r r s r r s r)
     (s s r r r r s s r r r r r)
     (r s r s s r s s r s s r s)
     (s r r s s r r r r s s r r)
     (r r r s s r r r r s s r r)
     (s s r r s s s s s s r r s)
     (r r r s r s s s s r s r r)
     (r r r s r s r r s r s r r)
     (s r r r s s s s s s r r r))
    ((r r r r s r r s s s s r r s s)
     (r s s s r r r s r r r r r r r)
     (r s s s r r r s r r r r r r r)
     (r r r r s r r s s s s r r s s)
     (r r r s s r r r s s s r r s s)
     (r r r s s r s s r r s r r s r)
     (s s s r s r s s r s r s s r s)
     (s r r r s r r r r r s r r s r)
     (r s r r r s s s r s r r r r s)
     (r s r r r s s r r s r s s r s)
     (r r r r r s s r r s r s s r s)
     (r s s r r s s r s s r s s s s)
     (r r r s r s r s r s r s s r s))
    ((r s r s r r r)
     (s r r s r s s)
     (s r r r r s s)
     (r s r s r r r)
     (r r r s s s s)
     (r r s r s s s)
     (r s s s s s s)
     (r r r r r s s)
     (s s s s s r r)
     (s s r s r s s)
     (r s r s s r r))
    ((r r s r r s r r s r r s r r s s s)
     (s r r s r s s s s r s r r s r r r)
     (r r r s r r s s r r s r r r s r r)
     (r r r s s s r r s s s r r r r r r)
     (r r s r s s r r s s r s r r r r r)
     (s r r s r s r r s r s r r s r r r)
     (r s s r s r s s r s r s s s r s s)
     (s s s s s s r r s s s s s s s r r)
     (s r s s s s r r s s s s r s r s s))
    ((s s s r r r s r s r r s r)
     (r s s r s r r s r r r r r)
     (r s r s r r r s r s r s s)
     (r r s r r r r r r r s s r)
     (r r s s r r r r r r s s r)
     (s s s r r s r r r r r r s)
     (s r s r s s s r s r s s r)
     (s r s r s s s r s r s s r)
     (s s s r r s r r r r r r s)
     (r r s s r r r r r r s s r)
     (r r s r r r r r r r s s r))
    ((r r r s s r r r r s r r r)
     (s r r r r r r s s r s s s)
     (s r r r r r r s s r s s s)
     (r r r s s r r r r s r r r)
     (s s s s s s s s r r s r s)
     (s r r r r r r s r s r r s)
     (s r s s s r r s s s s s r))
    ((s s s s r r r r s s s s s)
     (r r r r s s s s r r r r s)
     (s s s s r s s r s s s s r)
     (r s s r r r r r r s s r s)
     (r s s r s r r s r s s r r)
     (s s r s r s s r s r s s s)
     (r s s r r s s r r s s r r)
     (s s s s r s s r s s s s s)
     (s s s s s s s s s s s s r)
     (r s s r s r r s r s s r r)
     (s r r s r s s r s r r s s)
     (r r r r s s s s r r r r s)
     (s r r s s r r s s r r s s))
    ((s r s r s s r r r s r r r r r r s)
     (s s r r r r s r r s s r s s r s r)
     (r s r s s s s s r r r r s s s s s)
     (r s s s s r s r r s r s s s s s r)
     (r r r s s s s r s s r s s s s r r)
     (r r r s s s s r s s r s s s s r r)
     (r s s s s r s r r s r s s s s s r)
     (r s r s s s s s r r r r s s s s s)
     (s s r s r r s r r s s r s s r s r)
     (s r s r s s r r r s r r r r r r s)
     (r r r s s s s s s r r s r s r s s)
     (r r r r r r r s r r s s r r r r s)
     (r r r r r r r s r r s s r r r r s)
     (r r r s s s s s s r r s r s r s s)
     (s r s r s s r r r s r r r r r r s)
     (s s r s r r s r r s s r s s r s r)
     (r s r s s s s s r r r r s s s s s))
    ((r s s r s s s s r s s r r)
     (s s r r s s s s r r s s s)
     (r s r s s s s s s r s r r)
     (s r s r r s s r r s r s s)
     (r r s s s s s s s s r r r)
     (r s s s s s s s s s s r r)
     (s r s r s s s s r s r s s)
     (r s r r s s s s r r s r r)
     (r r r r s s s s r r r r r)
     (s r s r s s s s r s r s s)
     (r s r s r r r r s r s r r)
     (r s s r r s s r r s s r r)
     (s r r r r s s r r r r s s)
     (r r s s r s s r s s s r r)
     (s s s r s s s s r s s s s))
    ((s r r r r s r r s r r r r s r s s)
     (r r r r s r r r r s r r r r s s s)
     (r s r r s s s s r s r r s r r s r)
     (s s r s r r s s r r s r s s s r r)
     (r r r r r s s s s r r r r r r s s)
     (r s s s r s s s s r s s s r r r r)
     (s s r r s s s s s s r r s s r s r)
     (r r r s r r s s r r s r r r s s s)
     (r r r s r r s s r r s r r r s s s))
    ((s s r s r s s r r r s r s)
     (s s r s r s s r r r s r s)
     (r r r r r s r r s s s s r)
     (s r s s r r s s s r r r r)
     (r s r s r r s r r s r s r)
     (r r s s r r r r r s r s r)
     (s r s s r r r r s r s r r)
     (r s s r s s r s r r s s r)
     (r s s r s s r s r r s s r)
     (r r s s r r r r s r s r r)
     (r r s s r r r r r s r s r)
     (r s r s r r s r r s r s r)
     (s r s s r r s s s r r r r)
     (r r r r r s r r s s s s r)
     (s s r s r s s r r r s r s))
    ((r r s r s r s s r r r r s)
     (s s r r s s s s s r s s r)
     (s s r r s s s s s r s s r)
     (r r s r s r s s r r r r s)
     (s r s r r r r r r s s r r)
     (s r s r s r s s s r s r s)
     (r r r s r s r r r r r s r)
     (r s s r r s r s r r s s s)
     (s r r s r r r r r s r r r)
     (r s r r s r r r r s r s r)
     (r s r r s r r s r s r s r)
     (s r r s r r r r r s r r r)
     (r s s r r s r s r r s s s)
     (r r r s r s r r r r r s r)
     (s r s r s r s s s r s r s)
     (s r s r r r r r r s s r r)
     (r r s r s r s s r r r r s))
    ((r r r r r s r)
     (s s s s s s r)
     (s r r s r s r)
     (s s s s s r r)
     (s r r s r r r)
     (r s s r s s r)
     (s r r s s s s)
     (s r r r r s s)
     (r r r r s r r)
     (s r r s r s s)
     (s s s s s r s)
     (r s s r r s s)
     (r r r r r r s)
     (s s s s s r s)
     (r s s r s s r)
     (r s s r s s r)
     (s s s s s r s))))

(printf "~a~n" (solve1 INPUT))
(printf "~a~n" (solve2 INPUT))
